import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type GranadaLanguage = 'es' | 'en' | 'pt';

interface GranadaLanguageContextType {
  language: GranadaLanguage;
  setLanguage: (lang: GranadaLanguage) => void;
  t: (key: string) => string;
}

const translations: Record<GranadaLanguage, Record<string, string>> = {
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.inmobiliarias': 'Inmobiliarias y Admin',
    'nav.propietarios': 'Propietarios',
    'nav.planes': 'Planes',
    'nav.proveedores': 'Proveedores',
    'nav.contacto': 'Contacto',
    'nav.access_pms': 'Acceso PMS',
    
    // Home page
    'home.badge': 'Property Management System',
    'home.title': 'La forma simple de administrar propiedades complejas',
    'home.subtitle': 'Plataforma integral para la gestión de alquileres que conecta inmobiliarias, propietarios e inquilinos en un solo lugar.',
    'home.benefit1': 'Control total de contratos y pagos',
    'home.benefit2': 'Seguridad y transparencia garantizada',
    'home.benefit3': 'Reportes automáticos mensuales',
    'home.cta_inmobiliaria': 'Inmobiliaria / Admin',
    'home.cta_propietario': 'Propietario',
    
    // Inmobiliarias page
    'inmobiliarias.badge': 'Para Inmobiliarias y Administradores',
    'inmobiliarias.title': 'Potenciá tu Inmobiliaria con Granada',
    'inmobiliarias.subtitle': 'Centralizá toda la gestión de propiedades, contratos y pagos en una plataforma profesional. Ofrecé un servicio premium a tus clientes con reportes automáticos y transparencia total.',
    'inmobiliarias.view_plans': 'Ver Planes',
    'inmobiliarias.request_demo': 'Solicitar Demo',
    'inmobiliarias.why_granada': '¿Por qué Granada para tu Inmobiliaria?',
    'inmobiliarias.why_granada_subtitle': 'Dejá atrás las planillas de Excel, los WhatsApp desorganizados y las capturas de pantalla perdidas.',
    'inmobiliarias.benefit1_title': 'Gestión Centralizada',
    'inmobiliarias.benefit1_desc': 'Administrá todas tus propiedades, contratos y pagos desde una única plataforma. Sin papeles, sin planillas dispersas.',
    'inmobiliarias.benefit2_title': 'Portal para Clientes',
    'inmobiliarias.benefit2_desc': 'Ofrecé a tus propietarios un portal personalizado donde ven reportes, gastos y el estado de sus propiedades en tiempo real.',
    'inmobiliarias.benefit3_title': 'Automatización Total',
    'inmobiliarias.benefit3_desc': 'Generá recibos, reportes mensuales y alertas automáticas. Enfocate en crecer, no en tareas repetitivas.',
    'inmobiliarias.benefit4_title': 'Red de Proveedores',
    'inmobiliarias.benefit4_desc': 'Accedé a una red de proveedores verificados para mantenimientos. Cotizá, aprobá y seguí todo en un solo lugar.',
    'inmobiliarias.benefit5_title': 'Valor Agregado Continuo',
    'inmobiliarias.benefit5_desc': 'No solo gestiones propiedades con contratos activos. Administrá gastos mensuales (expensas, impuestos, servicios) y mantenimientos incluso cuando están desocupadas. Fidelizá propietarios ofreciendo servicio integral.',
    'inmobiliarias.differentiator_badge': 'Diferenciador Clave',
    'inmobiliarias.differentiator_title': 'Administrá Propiedades Desocupadas',
    'inmobiliarias.differentiator_subtitle': 'Ofrecé valor agregado continuo a tus propietarios, no solo cuando hay contratos activos.',
    'inmobiliarias.problem_title': 'El Problema Tradicional',
    'inmobiliarias.problem1': 'Software que solo funciona con contratos activos',
    'inmobiliarias.problem2': 'Propiedades vacías = pérdida de visibilidad y control',
    'inmobiliarias.problem3': 'Gastos mensuales dispersos en planillas o emails',
    'inmobiliarias.problem4': 'Propietarios sin reportes durante vacancia',
    'inmobiliarias.solution_title': 'La Solución Granada',
    'inmobiliarias.solution1_title': 'Administrá propiedades sin contrato',
    'inmobiliarias.solution1_desc': 'Registrá gastos mensuales (expensas, impuestos, servicios)',
    'inmobiliarias.solution2_title': 'Gestioná mantenimientos y reparaciones',
    'inmobiliarias.solution2_desc': 'Con aprobación de propietarios y seguimiento',
    'inmobiliarias.solution3_title': 'Reportes mensuales automáticos',
    'inmobiliarias.solution3_desc': 'Incluso durante períodos de vacancia',
    'inmobiliarias.solution4_title': 'Búsqueda de inquilinos en paralelo',
    'inmobiliarias.solution4_desc': 'Mientras administrás los gastos de la propiedad',
    'inmobiliarias.result': 'Resultado:',
    'inmobiliarias.result_desc': 'Fidelizás propietarios con servicio integral continuo, no solo cuando hay alquiler activo. Te diferenciás de la competencia.',
    'inmobiliarias.modules_title': 'Módulos que Potencian tu Gestión',
    'inmobiliarias.modules_subtitle': 'Todo lo que necesitás para administrar propiedades de forma profesional, en un solo lugar.',
    'inmobiliarias.module1_title': 'Propiedades',
    'inmobiliarias.module1_desc': 'Registro completo con fotos, documentos y historial de cada inmueble.',
    'inmobiliarias.module2_title': 'Contratos',
    'inmobiliarias.module2_desc': 'Creá contratos con ajustes por IPC/ICL, renovaciones y seguimiento automático.',
    'inmobiliarias.module3_title': 'Pagos',
    'inmobiliarias.module3_desc': 'Calendario de vencimientos, carga de comprobantes y conciliación bancaria.',
    'inmobiliarias.module4_title': 'Mantenimientos',
    'inmobiliarias.module4_desc': 'Gestioná reparaciones, aprobaciones de propietarios y seguimiento de proveedores.',
    'inmobiliarias.module5_title': 'Reportes',
    'inmobiliarias.module5_desc': 'Informes mensuales automáticos para propietarios con desglose de ingresos y gastos.',
    'inmobiliarias.module6_title': 'Multi-tenant',
    'inmobiliarias.module6_desc': 'Roles y permisos granulares. Cada inmobiliaria con su espacio aislado y seguro.',
    'inmobiliarias.cta_title': 'Empezá a profesionalizar tu gestión hoy',
    'inmobiliarias.cta_subtitle': 'Crecé en propiedades sin crecer en problemas. Granada escala con vos, desde las primeras 5 propiedades hasta cientos de unidades.',
    'inmobiliarias.view_plans_prices': 'Ver Planes y Precios',
    'inmobiliarias.schedule_demo': 'Agendar Demo Gratuita',
    
    // Propietarios page
    'propietarios.badge': 'Para Propietarios',
    'propietarios.title': 'Gestioná o Delegá tus Propiedades con Transparencia Total',
    'propietarios.subtitle': 'Elegí tu camino: administrá vos mismo con todas las herramientas profesionales, o delegá en una inmobiliaria y monitoreá todo en tiempo real.',
    'propietarios.two_ways_title': 'Dos Formas de Usar Granada',
    'propietarios.two_ways_subtitle': 'La tecnología es la misma. Vos elegís el nivel de involucramiento.',
    'propietarios.self_title': 'Auto-Gestión',
    'propietarios.self_subtitle': 'Administrá vos mismo',
    'propietarios.self_desc': 'Accedé a tu portal Granada para gestionar tus propiedades de forma directa. Creá contratos, cargá pagos, aprobá mantenimientos y generá reportes.',
    'propietarios.self_feature1': 'Control total de tus alquileres',
    'propietarios.self_feature2': 'Sin comisiones de administración',
    'propietarios.self_feature3': 'Todas las herramientas profesionales',
    'propietarios.self_feature4': 'Soporte técnico incluido',
    'propietarios.delegate_title': 'Delegación',
    'propietarios.delegate_subtitle': 'Dejá que profesionales lo hagan',
    'propietarios.delegate_desc': 'Asignale la gestión a una Inmobiliaria que use Granada. Vos monitoreás todo en tiempo real desde tu portal, sin perder visibilidad.',
    'propietarios.delegate_feature1': 'Inmobiliarias profesionales verificadas',
    'propietarios.delegate_feature2': 'Transparencia total en tiempo real',
    'propietarios.delegate_feature3': 'Reportes mensuales automáticos',
    'propietarios.delegate_feature4': 'Menos estrés, más tranquilidad',
    'propietarios.vacancy_title': 'Tu Propiedad Siempre Gestionada',
    'propietarios.vacancy_intro': 'Incluso cuando tu propiedad está desocupada',
    'propietarios.vacancy_intro_detail': ', seguís teniendo gastos mensuales: expensas, impuestos, servicios, y posibles reparaciones.',
    'propietarios.vacancy_desc': 'Con Granada, tu inmobiliaria (o vos mismo) puede registrar y administrar todos estos gastos mientras se busca un nuevo inquilino.',
    'propietarios.vacancy_highlight': 'No perdés visibilidad ni control',
    'propietarios.vacancy_highlight_detail': ' en los períodos de vacancia.',
    'propietarios.vacancy_item1_title': 'Registro de gastos mensuales',
    'propietarios.vacancy_item1_desc': 'Expensas, ABL, servicios',
    'propietarios.vacancy_item2_title': 'Mantenimientos y reparaciones',
    'propietarios.vacancy_item2_desc': 'Con aprobación y seguimiento',
    'propietarios.vacancy_item3_title': 'Reportes mensuales',
    'propietarios.vacancy_item3_desc': 'Incluso sin inquilino activo',
    'propietarios.vacancy_item4_title': 'Búsqueda en paralelo',
    'propietarios.vacancy_item4_desc': 'Mientras gestionan tus gastos',
    'propietarios.portal_title': 'Tu Portal de Propietario',
    'propietarios.portal_subtitle': 'Todo lo que necesitás saber sobre tu propiedad, en un solo lugar.',
    'propietarios.benefit1_title': 'Reportes Automáticos',
    'propietarios.benefit1_desc': 'Recibí cada mes un informe detallado con ingresos, gastos y el estado de tu propiedad.',
    'propietarios.benefit2_title': 'Historial de Pagos',
    'propietarios.benefit2_desc': 'Consultá todos los pagos históricos, comprobantes y estado de cuenta en un solo lugar.',
    'propietarios.benefit3_title': 'Aprobación de Gastos',
    'propietarios.benefit3_desc': 'Revisá y aprobá mantenimientos y gastos extraordinarios desde tu portal.',
    'propietarios.benefit4_title': 'Documentación Central',
    'propietarios.benefit4_desc': 'Contratos, recibos, fotos y documentos de tu propiedad siempre disponibles.',
    'propietarios.benefit5_title': 'Actualizaciones en Tiempo Real',
    'propietarios.benefit5_desc': 'Seguí el estado de tu propiedad y contratos sin llamadas ni mensajes.',
    'propietarios.benefit6_title': 'Seguridad y Privacidad',
    'propietarios.benefit6_desc': 'Tus datos protegidos con encriptación y acceso exclusivo para vos.',
    'propietarios.benefit7_title': 'Administración Continua',
    'propietarios.benefit7_desc': 'Tu propiedad está gestionada profesionalmente incluso cuando está desocupada. Seguimiento de expensas, impuestos, servicios y mantenimientos mientras se buscan nuevos inquilinos.',
    'propietarios.cta_title': 'Empezá a gestionar con claridad',
    'propietarios.cta_subtitle': 'Dejá atrás los papeles perdidos y las dudas. Con Granada, todo está claro, ordenado y disponible cuando lo necesitás.',
    'propietarios.cta_access': 'Solicitar Acceso',
    'propietarios.cta_agency': '¿Sos Inmobiliaria?',
    
    // Proveedores page
    'proveedores.badge': 'Red de Proveedores',
    'proveedores.title': 'Red de Proveedores Confiables',
    'proveedores.subtitle': 'Conectamos inmobiliarias con proveedores verificados. Más trabajo para profesionales, mejor servicio para las propiedades.',
    'proveedores.categories_title': 'Categorías de Servicios',
    'proveedores.categories_subtitle': 'Encontrá el proveedor indicado para cada tipo de mantenimiento.',
    'proveedores.cat1_title': 'Plomería',
    'proveedores.cat1_desc': 'Reparaciones, instalaciones y mantenimiento de sistemas de agua',
    'proveedores.cat2_title': 'Electricidad',
    'proveedores.cat2_desc': 'Instalaciones eléctricas, reparaciones y emergencias',
    'proveedores.cat3_title': 'Pintura',
    'proveedores.cat3_desc': 'Pintura interior/exterior, empapelado y revestimientos',
    'proveedores.cat4_title': 'Limpieza',
    'proveedores.cat4_desc': 'Limpieza profunda, mantenimiento y desinfección',
    'proveedores.cat5_title': 'Jardinería',
    'proveedores.cat5_desc': 'Mantenimiento de espacios verdes y parquización',
    'proveedores.cat6_title': 'Cerrajería',
    'proveedores.cat6_desc': 'Cambio de cerraduras, llaves y sistemas de seguridad',
    'proveedores.benefits_title': 'Un Ecosistema que Beneficia a Todos',
    'proveedores.for_agencies': 'Para Inmobiliarias',
    'proveedores.for_agencies_desc': 'Accedé a proveedores verificados y confiables. Cotizá, aprobá y seguí todos los trabajos desde Granada sin llamadas ni mensajes.',
    'proveedores.agency_feature1': 'Proveedores pre-verificados',
    'proveedores.agency_feature2': 'Comparación de presupuestos',
    'proveedores.agency_feature3': 'Seguimiento en tiempo real',
    'proveedores.agency_feature4': 'Historial de trabajos',
    'proveedores.for_providers': 'Para Proveedores',
    'proveedores.for_providers_desc': 'Recibí más trabajo de inmobiliarias profesionales. Gestioná pedidos, presupuestos y pagos de forma ordenada.',
    'proveedores.provider_feature1': 'Acceso a múltiples inmobiliarias',
    'proveedores.provider_feature2': 'Agenda de trabajos organizada',
    'proveedores.provider_feature3': 'Pagos seguros y en tiempo',
    'proveedores.provider_feature4': 'Reputación verificable',
    'proveedores.how_title': '¿Cómo Funciona el Sistema?',
    'proveedores.how_subtitle': 'Un proceso simple y transparente para todos los involucrados.',
    'proveedores.step1_title': 'Registro y Verificación',
    'proveedores.step1_desc': 'El proveedor se registra con su especialidad y documentación. Granada verifica credenciales y experiencia.',
    'proveedores.step2_title': 'Solicitud de Cotización',
    'proveedores.step2_desc': 'La inmobiliaria carga un mantenimiento necesario. Los proveedores de la categoría reciben la notificación.',
    'proveedores.step3_title': 'Presupuesto y Aprobación',
    'proveedores.step3_desc': 'El proveedor envía presupuesto. La inmobiliaria compara y aprueba. El propietario autoriza el gasto.',
    'proveedores.step4_title': 'Ejecución y Pago',
    'proveedores.step4_desc': 'El proveedor ejecuta el trabajo, sube fotos del resultado. Se procesa el pago a través de Granada.',
    'proveedores.cta_title': 'Unite a la Red Granada',
    'proveedores.cta_subtitle': '¿Sos proveedor de servicios para propiedades? Registrate y accedé a más trabajo con inmobiliarias profesionales que usan Granada.',
    'proveedores.cta_register': 'Registrarme como Proveedor',
    'proveedores.cta_directory': 'Ver Directorio de Proveedores',
    
    // Planes page
    'planes.badge': 'Planes y Precios',
    'planes.title': 'Elige el plan perfecto para tu negocio',
    'planes.subtitle': 'Planes flexibles que se adaptan al tamaño de tu cartera. Sin costos ocultos, sin compromisos a largo plazo.',
    'planes.billing_label': 'Suscripción con Pago',
    'planes.monthly': 'Mensual',
    'planes.yearly': 'Anual',
    'planes.off': 'OFF',
    'planes.equivalent': 'Equivalente a',
    'planes.per_month': '/mes',
    'planes.per_year': '/año',
    'planes.start': 'Comenzar',
    'planes.contact': 'Contactar',
    'planes.popular': 'Más Popular',
    'planes.faq_title': 'Preguntas Frecuentes',
    'planes.cta_title': '¿Listo para empezar?',
    'planes.cta_subtitle': 'Agenda una demo personalizada o comienza tu prueba gratuita hoy.',
    'planes.cta_demo': 'Agendar Demo',
    'planes.cta_trial': 'Prueba Gratuita',
    'planes.vat_note': 'Los valores expresados no incluyen IVA',
    'planes.plan_basic': 'Básico',
    'planes.plan_professional': 'Profesional',
    'planes.plan_enterprise': 'Enterprise',
    'planes.plan_basic_desc': 'Plan ideal para pequeños propietarios o administradores individuales',
    'planes.plan_professional_desc': 'Para inmobiliarias o administradoras medianas con múltiples propiedades',
    'planes.plan_enterprise_desc': 'Solución completa para grandes inmobiliarias y corporativos',
    'planes.feature_properties': 'Hasta {n} propiedad',
    'planes.feature_properties_plural': 'Hasta {n} propiedades',
    'planes.feature_contracts': 'Hasta {n} contratos simultáneos',
    'planes.feature_users': '{n} usuarios activos',
    'planes.feature_branches': 'Hasta {n} sucursales',
    'planes.feature_basic_reports': 'Reportes básicos',
    'planes.feature_advanced_reports': 'Reportes avanzados',
    'planes.feature_advanced_reports_unlimited': 'Reportes avanzados ilimitados',
    'planes.feature_storage': '{n} GB almacenamiento',
    'planes.feature_email_support': 'Soporte por email',
    'planes.feature_priority_support': 'Soporte prioritario',
    'planes.feature_priority_support_24': 'Soporte prioritario 24/7',
    'planes.feature_analytics': 'Analytics avanzados',
    'planes.feature_analytics_bi': 'Analytics avanzados con BI',
    'planes.feature_api': 'API access ({n} calls/día)',
    'planes.feature_api_unlimited': 'API access ilimitado',
    'planes.feature_bulk': 'Operaciones masivas',
    'planes.feature_branding': 'Branding personalizado',
    'planes.feature_notifications': 'Notificaciones personalizadas',
    'planes.feature_whitelabel': 'Whitelabel (sin marca Granada)',
    'planes.request_plan': 'Solicitar Plan',
    'planes.faq1_q': '¿Puedo cambiar de plan en cualquier momento?',
    'planes.faq1_a': 'Sí, podés upgradear o downgradear tu plan cuando quieras. Los cambios se aplican en el siguiente período de facturación.',
    'planes.faq2_q': '¿Qué incluye cada plan?',
    'planes.faq2_a': 'Plan Básico: ideal para pequeños propietarios con hasta 1 propiedad y 2 contratos. Plan Profesional: para inmobiliarias medianas con hasta 5 propiedades, 10 contratos y funcionalidades avanzadas. Plan Enterprise: solución completa con hasta 15 propiedades, 30 contratos y soporte prioritario 24/7.',
    'planes.faq3_q': '¿Los precios incluyen IVA?',
    'planes.faq3_a': 'No, los precios mostrados no incluyen IVA. Se factura mensualmente con todos los comprobantes fiscales correspondientes.',
    'planes.faq4_q': '¿Qué pasa si supero el límite de propiedades o contratos?',
    'planes.faq4_a': 'Te avisamos cuando te acerques al límite. Podés upgradear tu plan en cualquier momento para seguir agregando propiedades y contratos sin interrupciones.',
    'planes.faq5_q': '¿Cómo funciona el soporte técnico?',
    'planes.faq5_a': 'Plan Básico: soporte por email. Plan Profesional: soporte por email con prioridad. Plan Enterprise: soporte prioritario 24/7 con atención personalizada.',
    
    // Contacto page
    'contacto.badge': 'Contáctanos',
    'contacto.title': '¿Cómo podemos ayudarte?',
    'contacto.subtitle': 'Estamos aquí para responder tus consultas sobre Granada Platform',
    'contacto.form_title': 'Envíanos un mensaje',
    'contacto.info_title': 'Otras formas de contacto',
    'contacto.email': 'Email',
    'contacto.email_desc': 'Escríbenos y te responderemos pronto',
    'contacto.phone': 'Teléfono',
    'contacto.phone_desc': 'Llámanos en horario de atención',
    'contacto.office': 'Oficina',
    'contacto.office_desc': 'Visítanos en nuestra ubicación',
    'contacto.hours': 'Horarios',
    'contacto.hours_desc': 'Estamos disponibles',
    'contacto.hours_weekdays': 'Lunes a Viernes: 9:00 - 18:00',
    'contacto.hours_saturday': 'Sábados: 9:00 - 13:00',
    'contacto.toast_success': '¡Mensaje enviado!',
    'contacto.toast_success_desc': 'Te contactaremos en las próximas 24-48 horas.',
    'contacto.toast_error': 'Error',
    'contacto.toast_error_desc': 'No se pudo enviar el mensaje. Intenta nuevamente.',
    
    // Footer
    'footer.rights': 'Todos los derechos reservados',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    
    // Final CTA Section
    'cta.title': '¿Listo para transformar tu gestión inmobiliaria?',
    'cta.subtitle': 'Únete a las inmobiliarias que ya confían en Granada para simplificar su operación diaria.',
    'cta.card1_title': 'Inmobiliarias y Administradores',
    'cta.card1_desc': 'Descubre cómo Granada puede optimizar tu gestión de propiedades.',
    'cta.card1_button': 'Ver Soluciones',
    'cta.card2_title': 'Propietarios',
    'cta.card2_desc': 'Mantén el control de tus inversiones con reportes automáticos.',
    'cta.card2_button': 'Conocer Más',
    'cta.card3_title': '¿Tienes Dudas?',
    'cta.card3_desc': 'Nuestro equipo está listo para ayudarte.',
    'cta.card3_button': 'Contactar',
    
    // Lifecycle Section
    'lifecycle.title': 'Del aviso al contrato renovado, en una sola plataforma',
    'lifecycle.subtitle': 'Granada ordena la relación entre Propietario, Propiedad, Inquilino, Contrato, Firmas, Pagos, Cobros, Renovaciones y Proveedores. Un flujo claro, sin depender de 20 Excels y 15 grupos de WhatsApp.',
    'lifecycle.step1_title': 'Captar y preparar la propiedad',
    'lifecycle.step1_desc': 'Cargás la propiedad con datos clave: ubicación, tipo de alquiler, valor, moneda, inventario, fotos, documentación. Definís Propietario, Inmobiliaria/Administrador y distribución de fondos.',
    'lifecycle.step2_title': 'Publicación y selección de inquilino',
    'lifecycle.step2_desc': 'Integrás Granada con portales, recibís interesados, registrás candidatos, requisitos y decisiones. Todo el contexto en el sistema.',
    'lifecycle.step3_title': 'Contrato y firmas',
    'lifecycle.step3_desc': 'Generás el contrato desde Granada con todos los datos clave. Gestionás firmas digitales o presenciales, todo documentado.',
    'lifecycle.step4_title': 'Pagos y cobros mensuales',
    'lifecycle.step4_desc': 'Granada calcula importes, genera recordatorios, registra pagos/atrasos, distribuye montos según honorarios, comisiones, retenciones.',
    'lifecycle.step5_title': 'Gastos, mantenimientos y proveedores',
    'lifecycle.step5_desc': 'Creás órdenes de trabajo, asignás proveedores, registrás presupuestos. El propietario aprueba y todo queda asociado.',
    'lifecycle.step6_title': 'Reportes y relación con el propietario',
    'lifecycle.step6_desc': 'Cada mes: reporte claro de alquileres, gastos, comisiones y saldo neto. Portal de Propietario para más detalle.',
    'lifecycle.step7_title': 'Renovaciones, actualizaciones y cierre',
    'lifecycle.step7_desc': 'Granada avisa vencimientos, opciones de renovación, índices de actualización. Todo el historial disponible.',
    
    // Role Views Section
    'roles.title': 'Una vista para cada rol',
    'roles.admin_title': 'Inmobiliaria / Administrador',
    'roles.admin_desc': 'Tablero global, KPIs de cobros/gastos/rentabilidad, gestión de renovaciones y proveedores',
    'roles.admin_feature1': 'Dashboard con métricas clave',
    'roles.admin_feature2': 'Gestión de múltiples propiedades',
    'roles.admin_feature3': 'Control de vencimientos',
    'roles.admin_feature4': 'Coordinación de proveedores',
    'roles.owner_title': 'Propietario',
    'roles.owner_desc': 'Resúmenes mensuales, contratos y vencimientos, historial de cobros y gastos',
    'roles.owner_feature1': 'Reportes mensuales automáticos',
    'roles.owner_feature2': 'Visibilidad total de ingresos/gastos',
    'roles.owner_feature3': 'Historial completo por propiedad',
    'roles.owner_feature4': 'Aprobación de gastos extraordinarios',
    'roles.tenant_title': 'Inquilino',
    'roles.tenant_desc': 'Contrato y pagos en un solo lugar, recordatorios, canal para reportar problemas',
    'roles.tenant_feature1': 'Acceso a contrato digital',
    'roles.tenant_feature2': 'Historial de pagos',
    'roles.tenant_feature3': 'Recordatorios automáticos',
    'roles.tenant_feature4': 'Reporte de mantenimientos',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.inmobiliarias': 'Real Estate & Admin',
    'nav.propietarios': 'Property Owners',
    'nav.planes': 'Plans',
    'nav.proveedores': 'Providers',
    'nav.contacto': 'Contact',
    'nav.access_pms': 'PMS Access',
    
    // Home page
    'home.badge': 'Property Management System',
    'home.title': 'The simple way to manage complex properties',
    'home.subtitle': 'Comprehensive rental management platform that connects real estate agencies, property owners, and tenants in one place.',
    'home.benefit1': 'Full control of contracts and payments',
    'home.benefit2': 'Guaranteed security and transparency',
    'home.benefit3': 'Automatic monthly reports',
    'home.cta_inmobiliaria': 'Real Estate / Admin',
    'home.cta_propietario': 'Property Owner',
    
    // Inmobiliarias page
    'inmobiliarias.badge': 'For Real Estate Agencies and Administrators',
    'inmobiliarias.title': 'Empower Your Real Estate Agency with Granada',
    'inmobiliarias.subtitle': 'Centralize all property, contract, and payment management in one professional platform. Offer premium service to your clients with automatic reports and total transparency.',
    'inmobiliarias.view_plans': 'View Plans',
    'inmobiliarias.request_demo': 'Request Demo',
    'inmobiliarias.why_granada': 'Why Granada for Your Agency?',
    'inmobiliarias.why_granada_subtitle': 'Leave behind Excel spreadsheets, disorganized WhatsApp messages, and lost screenshots.',
    'inmobiliarias.benefit1_title': 'Centralized Management',
    'inmobiliarias.benefit1_desc': 'Manage all your properties, contracts, and payments from a single platform. No papers, no scattered spreadsheets.',
    'inmobiliarias.benefit2_title': 'Client Portal',
    'inmobiliarias.benefit2_desc': 'Offer your property owners a personalized portal where they can see reports, expenses, and the status of their properties in real time.',
    'inmobiliarias.benefit3_title': 'Total Automation',
    'inmobiliarias.benefit3_desc': 'Generate receipts, monthly reports, and automatic alerts. Focus on growing, not on repetitive tasks.',
    'inmobiliarias.benefit4_title': 'Provider Network',
    'inmobiliarias.benefit4_desc': 'Access a network of verified providers for maintenance. Quote, approve, and track everything in one place.',
    'inmobiliarias.benefit5_title': 'Continuous Added Value',
    'inmobiliarias.benefit5_desc': 'Manage not only properties with active contracts. Handle monthly expenses (HOA fees, taxes, utilities) and maintenance even when vacant. Retain property owners by offering comprehensive service.',
    'inmobiliarias.differentiator_badge': 'Key Differentiator',
    'inmobiliarias.differentiator_title': 'Manage Vacant Properties',
    'inmobiliarias.differentiator_subtitle': 'Offer continuous added value to your property owners, not just when there are active contracts.',
    'inmobiliarias.problem_title': 'The Traditional Problem',
    'inmobiliarias.problem1': 'Software that only works with active contracts',
    'inmobiliarias.problem2': 'Empty properties = loss of visibility and control',
    'inmobiliarias.problem3': 'Monthly expenses scattered in spreadsheets or emails',
    'inmobiliarias.problem4': 'Owners without reports during vacancy',
    'inmobiliarias.solution_title': 'The Granada Solution',
    'inmobiliarias.solution1_title': 'Manage properties without contracts',
    'inmobiliarias.solution1_desc': 'Record monthly expenses (HOA fees, taxes, utilities)',
    'inmobiliarias.solution2_title': 'Handle maintenance and repairs',
    'inmobiliarias.solution2_desc': 'With owner approval and tracking',
    'inmobiliarias.solution3_title': 'Automatic monthly reports',
    'inmobiliarias.solution3_desc': 'Even during vacancy periods',
    'inmobiliarias.solution4_title': 'Tenant search in parallel',
    'inmobiliarias.solution4_desc': 'While managing property expenses',
    'inmobiliarias.result': 'Result:',
    'inmobiliarias.result_desc': 'You retain property owners with continuous comprehensive service, not just when there\'s an active lease. You differentiate yourself from the competition.',
    'inmobiliarias.modules_title': 'Modules that Boost Your Management',
    'inmobiliarias.modules_subtitle': 'Everything you need to manage properties professionally, in one place.',
    'inmobiliarias.module1_title': 'Properties',
    'inmobiliarias.module1_desc': 'Complete registry with photos, documents, and history for each property.',
    'inmobiliarias.module2_title': 'Contracts',
    'inmobiliarias.module2_desc': 'Create contracts with CPI/ICL adjustments, renewals, and automatic tracking.',
    'inmobiliarias.module3_title': 'Payments',
    'inmobiliarias.module3_desc': 'Due date calendar, receipt uploads, and bank reconciliation.',
    'inmobiliarias.module4_title': 'Maintenance',
    'inmobiliarias.module4_desc': 'Manage repairs, owner approvals, and provider tracking.',
    'inmobiliarias.module5_title': 'Reports',
    'inmobiliarias.module5_desc': 'Automatic monthly reports for owners with income and expense breakdown.',
    'inmobiliarias.module6_title': 'Multi-tenant',
    'inmobiliarias.module6_desc': 'Granular roles and permissions. Each agency with its own isolated and secure space.',
    'inmobiliarias.cta_title': 'Start professionalizing your management today',
    'inmobiliarias.cta_subtitle': 'Grow your properties without growing your problems. Granada scales with you, from the first 5 properties to hundreds of units.',
    'inmobiliarias.view_plans_prices': 'View Plans and Pricing',
    'inmobiliarias.schedule_demo': 'Schedule Free Demo',
    
    // Propietarios page
    'propietarios.badge': 'For Property Owners',
    'propietarios.title': 'Manage or Delegate Your Properties with Total Transparency',
    'propietarios.subtitle': 'Choose your path: manage yourself with all professional tools, or delegate to a real estate agency and monitor everything in real time.',
    'propietarios.two_ways_title': 'Two Ways to Use Granada',
    'propietarios.two_ways_subtitle': 'The technology is the same. You choose the level of involvement.',
    'propietarios.self_title': 'Self-Management',
    'propietarios.self_subtitle': 'Manage it yourself',
    'propietarios.self_desc': 'Access your Granada portal to manage your properties directly. Create contracts, record payments, approve maintenance, and generate reports.',
    'propietarios.self_feature1': 'Total control of your rentals',
    'propietarios.self_feature2': 'No administration fees',
    'propietarios.self_feature3': 'All professional tools',
    'propietarios.self_feature4': 'Technical support included',
    'propietarios.delegate_title': 'Delegation',
    'propietarios.delegate_subtitle': 'Let professionals handle it',
    'propietarios.delegate_desc': 'Assign management to a Real Estate Agency that uses Granada. You monitor everything in real time from your portal, without losing visibility.',
    'propietarios.delegate_feature1': 'Verified professional agencies',
    'propietarios.delegate_feature2': 'Total real-time transparency',
    'propietarios.delegate_feature3': 'Automatic monthly reports',
    'propietarios.delegate_feature4': 'Less stress, more peace of mind',
    'propietarios.vacancy_title': 'Your Property Always Managed',
    'propietarios.vacancy_intro': 'Even when your property is vacant',
    'propietarios.vacancy_intro_detail': ', you still have monthly expenses: HOA fees, taxes, utilities, and possible repairs.',
    'propietarios.vacancy_desc': 'With Granada, your real estate agency (or yourself) can record and manage all these expenses while looking for a new tenant.',
    'propietarios.vacancy_highlight': 'You don\'t lose visibility or control',
    'propietarios.vacancy_highlight_detail': ' during vacancy periods.',
    'propietarios.vacancy_item1_title': 'Monthly expense recording',
    'propietarios.vacancy_item1_desc': 'HOA fees, property tax, utilities',
    'propietarios.vacancy_item2_title': 'Maintenance and repairs',
    'propietarios.vacancy_item2_desc': 'With approval and tracking',
    'propietarios.vacancy_item3_title': 'Monthly reports',
    'propietarios.vacancy_item3_desc': 'Even without an active tenant',
    'propietarios.vacancy_item4_title': 'Parallel search',
    'propietarios.vacancy_item4_desc': 'While managing your expenses',
    'propietarios.portal_title': 'Your Owner Portal',
    'propietarios.portal_subtitle': 'Everything you need to know about your property, in one place.',
    'propietarios.benefit1_title': 'Automatic Reports',
    'propietarios.benefit1_desc': 'Receive a detailed monthly report with income, expenses, and the status of your property.',
    'propietarios.benefit2_title': 'Payment History',
    'propietarios.benefit2_desc': 'Check all historical payments, receipts, and account status in one place.',
    'propietarios.benefit3_title': 'Expense Approval',
    'propietarios.benefit3_desc': 'Review and approve maintenance and extraordinary expenses from your portal.',
    'propietarios.benefit4_title': 'Central Documentation',
    'propietarios.benefit4_desc': 'Contracts, receipts, photos, and documents of your property always available.',
    'propietarios.benefit5_title': 'Real-Time Updates',
    'propietarios.benefit5_desc': 'Track your property and contract status without calls or messages.',
    'propietarios.benefit6_title': 'Security and Privacy',
    'propietarios.benefit6_desc': 'Your data protected with encryption and exclusive access for you.',
    'propietarios.benefit7_title': 'Continuous Administration',
    'propietarios.benefit7_desc': 'Your property is professionally managed even when vacant. Tracking of HOA fees, taxes, utilities, and maintenance while searching for new tenants.',
    'propietarios.cta_title': 'Start managing with clarity',
    'propietarios.cta_subtitle': 'Leave behind lost papers and doubts. With Granada, everything is clear, organized, and available when you need it.',
    'propietarios.cta_access': 'Request Access',
    'propietarios.cta_agency': 'Are you a Real Estate Agency?',
    
    // Proveedores page
    'proveedores.badge': 'Provider Network',
    'proveedores.title': 'Trusted Provider Network',
    'proveedores.subtitle': 'We connect real estate agencies with verified providers. More work for professionals, better service for properties.',
    'proveedores.categories_title': 'Service Categories',
    'proveedores.categories_subtitle': 'Find the right provider for each type of maintenance.',
    'proveedores.cat1_title': 'Plumbing',
    'proveedores.cat1_desc': 'Repairs, installations, and water system maintenance',
    'proveedores.cat2_title': 'Electrical',
    'proveedores.cat2_desc': 'Electrical installations, repairs, and emergencies',
    'proveedores.cat3_title': 'Painting',
    'proveedores.cat3_desc': 'Interior/exterior painting, wallpapering, and coatings',
    'proveedores.cat4_title': 'Cleaning',
    'proveedores.cat4_desc': 'Deep cleaning, maintenance, and disinfection',
    'proveedores.cat5_title': 'Landscaping',
    'proveedores.cat5_desc': 'Green space maintenance and landscaping',
    'proveedores.cat6_title': 'Locksmith',
    'proveedores.cat6_desc': 'Lock changes, keys, and security systems',
    'proveedores.benefits_title': 'An Ecosystem that Benefits Everyone',
    'proveedores.for_agencies': 'For Real Estate Agencies',
    'proveedores.for_agencies_desc': 'Access verified and reliable providers. Quote, approve, and track all work from Granada without calls or messages.',
    'proveedores.agency_feature1': 'Pre-verified providers',
    'proveedores.agency_feature2': 'Quote comparison',
    'proveedores.agency_feature3': 'Real-time tracking',
    'proveedores.agency_feature4': 'Work history',
    'proveedores.for_providers': 'For Providers',
    'proveedores.for_providers_desc': 'Receive more work from professional real estate agencies. Manage orders, quotes, and payments in an organized way.',
    'proveedores.provider_feature1': 'Access to multiple agencies',
    'proveedores.provider_feature2': 'Organized work schedule',
    'proveedores.provider_feature3': 'Secure and timely payments',
    'proveedores.provider_feature4': 'Verifiable reputation',
    'proveedores.how_title': 'How Does the System Work?',
    'proveedores.how_subtitle': 'A simple and transparent process for everyone involved.',
    'proveedores.step1_title': 'Registration and Verification',
    'proveedores.step1_desc': 'The provider registers with their specialty and documentation. Granada verifies credentials and experience.',
    'proveedores.step2_title': 'Quote Request',
    'proveedores.step2_desc': 'The agency uploads a required maintenance task. Providers in the category receive the notification.',
    'proveedores.step3_title': 'Quote and Approval',
    'proveedores.step3_desc': 'The provider sends a quote. The agency compares and approves. The owner authorizes the expense.',
    'proveedores.step4_title': 'Execution and Payment',
    'proveedores.step4_desc': 'The provider executes the work, uploads photos of the result. Payment is processed through Granada.',
    'proveedores.cta_title': 'Join the Granada Network',
    'proveedores.cta_subtitle': 'Are you a property service provider? Register and access more work with professional real estate agencies using Granada.',
    'proveedores.cta_register': 'Register as Provider',
    'proveedores.cta_directory': 'View Provider Directory',
    
    // Planes page
    'planes.badge': 'Plans & Pricing',
    'planes.title': 'Choose the perfect plan for your business',
    'planes.subtitle': 'Flexible plans that adapt to your portfolio size. No hidden costs, no long-term commitments.',
    'planes.billing_label': 'Payment Subscription',
    'planes.monthly': 'Monthly',
    'planes.yearly': 'Yearly',
    'planes.off': 'OFF',
    'planes.equivalent': 'Equivalent to',
    'planes.per_month': '/month',
    'planes.per_year': '/year',
    'planes.start': 'Get Started',
    'planes.contact': 'Contact',
    'planes.popular': 'Most Popular',
    'planes.faq_title': 'Frequently Asked Questions',
    'planes.cta_title': 'Ready to get started?',
    'planes.cta_subtitle': 'Schedule a personalized demo or start your free trial today.',
    'planes.cta_demo': 'Schedule Demo',
    'planes.cta_trial': 'Free Trial',
    'planes.vat_note': 'Prices shown do not include VAT',
    'planes.plan_basic': 'Basic',
    'planes.plan_professional': 'Professional',
    'planes.plan_enterprise': 'Enterprise',
    'planes.plan_basic_desc': 'Ideal plan for small property owners or individual administrators',
    'planes.plan_professional_desc': 'For medium-sized real estate agencies with multiple properties',
    'planes.plan_enterprise_desc': 'Complete solution for large real estate agencies and corporations',
    'planes.feature_properties': 'Up to {n} property',
    'planes.feature_properties_plural': 'Up to {n} properties',
    'planes.feature_contracts': 'Up to {n} simultaneous contracts',
    'planes.feature_users': '{n} active users',
    'planes.feature_branches': 'Up to {n} branches',
    'planes.feature_basic_reports': 'Basic reports',
    'planes.feature_advanced_reports': 'Advanced reports',
    'planes.feature_advanced_reports_unlimited': 'Unlimited advanced reports',
    'planes.feature_storage': '{n} GB storage',
    'planes.feature_email_support': 'Email support',
    'planes.feature_priority_support': 'Priority support',
    'planes.feature_priority_support_24': '24/7 priority support',
    'planes.feature_analytics': 'Advanced analytics',
    'planes.feature_analytics_bi': 'Advanced analytics with BI',
    'planes.feature_api': 'API access ({n} calls/day)',
    'planes.feature_api_unlimited': 'Unlimited API access',
    'planes.feature_bulk': 'Bulk operations',
    'planes.feature_branding': 'Custom branding',
    'planes.feature_notifications': 'Custom notifications',
    'planes.feature_whitelabel': 'Whitelabel (no Granada branding)',
    'planes.request_plan': 'Request Plan',
    'planes.faq1_q': 'Can I change my plan at any time?',
    'planes.faq1_a': 'Yes, you can upgrade or downgrade your plan at any time. Changes apply in the next billing period.',
    'planes.faq2_q': 'What does each plan include?',
    'planes.faq2_a': 'Basic Plan: ideal for small property owners with up to 1 property and 2 contracts. Professional Plan: for medium agencies with up to 5 properties, 10 contracts, and advanced features. Enterprise Plan: complete solution with up to 15 properties, 30 contracts, and 24/7 priority support.',
    'planes.faq3_q': 'Do prices include VAT?',
    'planes.faq3_a': 'No, prices shown do not include VAT. Billing is monthly with all corresponding tax receipts.',
    'planes.faq4_q': 'What happens if I exceed the property or contract limit?',
    'planes.faq4_a': 'We notify you when you approach the limit. You can upgrade your plan at any time to continue adding properties and contracts without interruption.',
    'planes.faq5_q': 'How does technical support work?',
    'planes.faq5_a': 'Basic Plan: email support. Professional Plan: priority email support. Enterprise Plan: 24/7 priority support with personalized attention.',
    
    // Contacto page
    'contacto.badge': 'Contact Us',
    'contacto.title': 'How can we help you?',
    'contacto.subtitle': 'We\'re here to answer your questions about Granada Platform',
    'contacto.form_title': 'Send us a message',
    'contacto.info_title': 'Other ways to contact',
    'contacto.email': 'Email',
    'contacto.email_desc': 'Write to us and we\'ll respond soon',
    'contacto.phone': 'Phone',
    'contacto.phone_desc': 'Call us during business hours',
    'contacto.office': 'Office',
    'contacto.office_desc': 'Visit us at our location',
    'contacto.hours': 'Hours',
    'contacto.hours_desc': 'We\'re available',
    'contacto.hours_weekdays': 'Monday to Friday: 9:00 AM - 6:00 PM',
    'contacto.hours_saturday': 'Saturday: 9:00 AM - 1:00 PM',
    'contacto.toast_success': 'Message sent!',
    'contacto.toast_success_desc': 'We\'ll contact you within 24-48 hours.',
    'contacto.toast_error': 'Error',
    'contacto.toast_error_desc': 'Could not send the message. Please try again.',
    
    // Footer
    'footer.rights': 'All rights reserved',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    
    // Final CTA Section
    'cta.title': 'Ready to transform your property management?',
    'cta.subtitle': 'Join the real estate agencies that already trust Granada to simplify their daily operations.',
    'cta.card1_title': 'Real Estate Agencies & Administrators',
    'cta.card1_desc': 'Discover how Granada can optimize your property management.',
    'cta.card1_button': 'View Solutions',
    'cta.card2_title': 'Property Owners',
    'cta.card2_desc': 'Stay in control of your investments with automatic reports.',
    'cta.card2_button': 'Learn More',
    'cta.card3_title': 'Have Questions?',
    'cta.card3_desc': 'Our team is ready to help you.',
    'cta.card3_button': 'Contact Us',
    
    // Lifecycle Section
    'lifecycle.title': 'From listing to contract renewal, in one platform',
    'lifecycle.subtitle': 'Granada organizes the relationship between Owner, Property, Tenant, Contract, Signatures, Payments, Collections, Renewals, and Providers. A clear flow, without depending on 20 spreadsheets and 15 WhatsApp groups.',
    'lifecycle.step1_title': 'Capture and prepare the property',
    'lifecycle.step1_desc': 'Load the property with key data: location, rental type, value, currency, inventory, photos, documentation. Define Owner, Real Estate/Administrator and fund distribution.',
    'lifecycle.step2_title': 'Publication and tenant selection',
    'lifecycle.step2_desc': 'Integrate Granada with portals, receive interested parties, register candidates, requirements, and decisions. All context in the system.',
    'lifecycle.step3_title': 'Contract and signatures',
    'lifecycle.step3_desc': 'Generate the contract from Granada with all key data. Manage digital or in-person signatures, everything documented.',
    'lifecycle.step4_title': 'Monthly payments and collections',
    'lifecycle.step4_desc': 'Granada calculates amounts, generates reminders, records payments/arrears, distributes amounts according to fees, commissions, withholdings.',
    'lifecycle.step5_title': 'Expenses, maintenance, and providers',
    'lifecycle.step5_desc': 'Create work orders, assign providers, record quotes. The owner approves and everything is associated.',
    'lifecycle.step6_title': 'Reports and owner relationship',
    'lifecycle.step6_desc': 'Every month: clear report of rentals, expenses, commissions, and net balance. Owner Portal for more detail.',
    'lifecycle.step7_title': 'Renewals, updates, and closure',
    'lifecycle.step7_desc': 'Granada notifies expirations, renewal options, update indexes. Full history available.',
    
    // Role Views Section
    'roles.title': 'A view for each role',
    'roles.admin_title': 'Real Estate / Administrator',
    'roles.admin_desc': 'Global dashboard, collection/expense/profitability KPIs, renewal and provider management',
    'roles.admin_feature1': 'Dashboard with key metrics',
    'roles.admin_feature2': 'Multi-property management',
    'roles.admin_feature3': 'Expiration control',
    'roles.admin_feature4': 'Provider coordination',
    'roles.owner_title': 'Property Owner',
    'roles.owner_desc': 'Monthly summaries, contracts and expirations, collection and expense history',
    'roles.owner_feature1': 'Automatic monthly reports',
    'roles.owner_feature2': 'Full visibility of income/expenses',
    'roles.owner_feature3': 'Complete history per property',
    'roles.owner_feature4': 'Extraordinary expense approval',
    'roles.tenant_title': 'Tenant',
    'roles.tenant_desc': 'Contract and payments in one place, reminders, channel to report issues',
    'roles.tenant_feature1': 'Digital contract access',
    'roles.tenant_feature2': 'Payment history',
    'roles.tenant_feature3': 'Automatic reminders',
    'roles.tenant_feature4': 'Maintenance reporting',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.inmobiliarias': 'Imobiliárias e Admin',
    'nav.propietarios': 'Proprietários',
    'nav.planes': 'Planos',
    'nav.proveedores': 'Fornecedores',
    'nav.contacto': 'Contato',
    'nav.access_pms': 'Acesso PMS',
    
    // Home page
    'home.badge': 'Property Management System',
    'home.title': 'A forma simples de administrar propriedades complexas',
    'home.subtitle': 'Plataforma integral para a gestão de aluguéis que conecta imobiliárias, proprietários e inquilinos em um só lugar.',
    'home.benefit1': 'Controle total de contratos e pagamentos',
    'home.benefit2': 'Segurança e transparência garantidas',
    'home.benefit3': 'Relatórios automáticos mensais',
    'home.cta_inmobiliaria': 'Imobiliária / Admin',
    'home.cta_propietario': 'Proprietário',
    
    // Inmobiliarias page
    'inmobiliarias.badge': 'Para Imobiliárias e Administradores',
    'inmobiliarias.title': 'Potencialize sua Imobiliária com Granada',
    'inmobiliarias.subtitle': 'Centralize toda a gestão de propriedades, contratos e pagamentos em uma plataforma profissional. Ofereça serviço premium aos seus clientes com relatórios automáticos e transparência total.',
    'inmobiliarias.view_plans': 'Ver Planos',
    'inmobiliarias.request_demo': 'Solicitar Demo',
    'inmobiliarias.why_granada': 'Por que Granada para sua Imobiliária?',
    'inmobiliarias.why_granada_subtitle': 'Deixe para trás as planilhas do Excel, os WhatsApp desorganizados e as capturas de tela perdidas.',
    'inmobiliarias.benefit1_title': 'Gestão Centralizada',
    'inmobiliarias.benefit1_desc': 'Administre todas as suas propriedades, contratos e pagamentos em uma única plataforma. Sem papéis, sem planilhas dispersas.',
    'inmobiliarias.benefit2_title': 'Portal para Clientes',
    'inmobiliarias.benefit2_desc': 'Ofereça aos seus proprietários um portal personalizado onde veem relatórios, despesas e o status de suas propriedades em tempo real.',
    'inmobiliarias.benefit3_title': 'Automação Total',
    'inmobiliarias.benefit3_desc': 'Gere recibos, relatórios mensais e alertas automáticos. Foque em crescer, não em tarefas repetitivas.',
    'inmobiliarias.benefit4_title': 'Rede de Fornecedores',
    'inmobiliarias.benefit4_desc': 'Acesse uma rede de fornecedores verificados para manutenções. Cotize, aprove e acompanhe tudo em um só lugar.',
    'inmobiliarias.benefit5_title': 'Valor Agregado Contínuo',
    'inmobiliarias.benefit5_desc': 'Não gerencie apenas propriedades com contratos ativos. Administre despesas mensais (condomínio, impostos, serviços) e manutenções mesmo quando estão desocupadas. Fidelize proprietários oferecendo serviço integral.',
    'inmobiliarias.differentiator_badge': 'Diferencial Chave',
    'inmobiliarias.differentiator_title': 'Administre Propriedades Desocupadas',
    'inmobiliarias.differentiator_subtitle': 'Ofereça valor agregado contínuo aos seus proprietários, não apenas quando há contratos ativos.',
    'inmobiliarias.problem_title': 'O Problema Tradicional',
    'inmobiliarias.problem1': 'Software que só funciona com contratos ativos',
    'inmobiliarias.problem2': 'Propriedades vazias = perda de visibilidade e controle',
    'inmobiliarias.problem3': 'Despesas mensais dispersas em planilhas ou emails',
    'inmobiliarias.problem4': 'Proprietários sem relatórios durante vacância',
    'inmobiliarias.solution_title': 'A Solução Granada',
    'inmobiliarias.solution1_title': 'Administre propriedades sem contrato',
    'inmobiliarias.solution1_desc': 'Registre despesas mensais (condomínio, impostos, serviços)',
    'inmobiliarias.solution2_title': 'Gerencie manutenções e reparos',
    'inmobiliarias.solution2_desc': 'Com aprovação de proprietários e acompanhamento',
    'inmobiliarias.solution3_title': 'Relatórios mensais automáticos',
    'inmobiliarias.solution3_desc': 'Mesmo durante períodos de vacância',
    'inmobiliarias.solution4_title': 'Busca de inquilinos em paralelo',
    'inmobiliarias.solution4_desc': 'Enquanto administra as despesas da propriedade',
    'inmobiliarias.result': 'Resultado:',
    'inmobiliarias.result_desc': 'Você fideliza proprietários com serviço integral contínuo, não apenas quando há aluguel ativo. Você se diferencia da concorrência.',
    'inmobiliarias.modules_title': 'Módulos que Potencializam sua Gestão',
    'inmobiliarias.modules_subtitle': 'Tudo o que você precisa para administrar propriedades de forma profissional, em um só lugar.',
    'inmobiliarias.module1_title': 'Propriedades',
    'inmobiliarias.module1_desc': 'Registro completo com fotos, documentos e histórico de cada imóvel.',
    'inmobiliarias.module2_title': 'Contratos',
    'inmobiliarias.module2_desc': 'Crie contratos com ajustes por índices, renovações e acompanhamento automático.',
    'inmobiliarias.module3_title': 'Pagamentos',
    'inmobiliarias.module3_desc': 'Calendário de vencimentos, upload de comprovantes e conciliação bancária.',
    'inmobiliarias.module4_title': 'Manutenções',
    'inmobiliarias.module4_desc': 'Gerencie reparos, aprovações de proprietários e acompanhamento de fornecedores.',
    'inmobiliarias.module5_title': 'Relatórios',
    'inmobiliarias.module5_desc': 'Relatórios mensais automáticos para proprietários com detalhamento de receitas e despesas.',
    'inmobiliarias.module6_title': 'Multi-tenant',
    'inmobiliarias.module6_desc': 'Papéis e permissões granulares. Cada imobiliária com seu espaço isolado e seguro.',
    'inmobiliarias.cta_title': 'Comece a profissionalizar sua gestão hoje',
    'inmobiliarias.cta_subtitle': 'Cresça em propriedades sem crescer em problemas. Granada escala com você, das primeiras 5 propriedades a centenas de unidades.',
    'inmobiliarias.view_plans_prices': 'Ver Planos e Preços',
    'inmobiliarias.schedule_demo': 'Agendar Demo Gratuita',
    
    // Propietarios page
    'propietarios.badge': 'Para Proprietários',
    'propietarios.title': 'Gerencie ou Delegue suas Propriedades com Transparência Total',
    'propietarios.subtitle': 'Escolha seu caminho: gerencie você mesmo com todas as ferramentas profissionais, ou delegue a uma imobiliária e monitore tudo em tempo real.',
    'propietarios.two_ways_title': 'Duas Formas de Usar Granada',
    'propietarios.two_ways_subtitle': 'A tecnologia é a mesma. Você escolhe o nível de envolvimento.',
    'propietarios.self_title': 'Autogestão',
    'propietarios.self_subtitle': 'Gerencie você mesmo',
    'propietarios.self_desc': 'Acesse seu portal Granada para gerenciar suas propriedades diretamente. Crie contratos, registre pagamentos, aprove manutenções e gere relatórios.',
    'propietarios.self_feature1': 'Controle total dos seus aluguéis',
    'propietarios.self_feature2': 'Sem comissões de administração',
    'propietarios.self_feature3': 'Todas as ferramentas profissionais',
    'propietarios.self_feature4': 'Suporte técnico incluído',
    'propietarios.delegate_title': 'Delegação',
    'propietarios.delegate_subtitle': 'Deixe profissionais fazerem',
    'propietarios.delegate_desc': 'Atribua a gestão a uma Imobiliária que usa Granada. Você monitora tudo em tempo real pelo seu portal, sem perder visibilidade.',
    'propietarios.delegate_feature1': 'Imobiliárias profissionais verificadas',
    'propietarios.delegate_feature2': 'Transparência total em tempo real',
    'propietarios.delegate_feature3': 'Relatórios mensais automáticos',
    'propietarios.delegate_feature4': 'Menos estresse, mais tranquilidade',
    'propietarios.vacancy_title': 'Sua Propriedade Sempre Gerenciada',
    'propietarios.vacancy_intro': 'Mesmo quando sua propriedade está desocupada',
    'propietarios.vacancy_intro_detail': ', você ainda tem despesas mensais: condomínio, impostos, serviços e possíveis reparos.',
    'propietarios.vacancy_desc': 'Com Granada, sua imobiliária (ou você mesmo) pode registrar e administrar todas essas despesas enquanto procura um novo inquilino.',
    'propietarios.vacancy_highlight': 'Você não perde visibilidade nem controle',
    'propietarios.vacancy_highlight_detail': ' nos períodos de vacância.',
    'propietarios.vacancy_item1_title': 'Registro de despesas mensais',
    'propietarios.vacancy_item1_desc': 'Condomínio, IPTU, serviços',
    'propietarios.vacancy_item2_title': 'Manutenções e reparos',
    'propietarios.vacancy_item2_desc': 'Com aprovação e acompanhamento',
    'propietarios.vacancy_item3_title': 'Relatórios mensais',
    'propietarios.vacancy_item3_desc': 'Mesmo sem inquilino ativo',
    'propietarios.vacancy_item4_title': 'Busca em paralelo',
    'propietarios.vacancy_item4_desc': 'Enquanto gerenciam suas despesas',
    'propietarios.portal_title': 'Seu Portal de Proprietário',
    'propietarios.portal_subtitle': 'Tudo o que você precisa saber sobre sua propriedade, em um só lugar.',
    'propietarios.benefit1_title': 'Relatórios Automáticos',
    'propietarios.benefit1_desc': 'Receba todo mês um relatório detalhado com receitas, despesas e o status da sua propriedade.',
    'propietarios.benefit2_title': 'Histórico de Pagamentos',
    'propietarios.benefit2_desc': 'Consulte todos os pagamentos históricos, comprovantes e extrato em um só lugar.',
    'propietarios.benefit3_title': 'Aprovação de Despesas',
    'propietarios.benefit3_desc': 'Revise e aprove manutenções e despesas extraordinárias pelo seu portal.',
    'propietarios.benefit4_title': 'Documentação Central',
    'propietarios.benefit4_desc': 'Contratos, recibos, fotos e documentos da sua propriedade sempre disponíveis.',
    'propietarios.benefit5_title': 'Atualizações em Tempo Real',
    'propietarios.benefit5_desc': 'Acompanhe o status da sua propriedade e contratos sem ligações nem mensagens.',
    'propietarios.benefit6_title': 'Segurança e Privacidade',
    'propietarios.benefit6_desc': 'Seus dados protegidos com criptografia e acesso exclusivo para você.',
    'propietarios.benefit7_title': 'Administração Contínua',
    'propietarios.benefit7_desc': 'Sua propriedade é gerenciada profissionalmente mesmo quando está desocupada. Acompanhamento de condomínio, impostos, serviços e manutenções enquanto buscam novos inquilinos.',
    'propietarios.cta_title': 'Comece a gerenciar com clareza',
    'propietarios.cta_subtitle': 'Deixe para trás os papéis perdidos e as dúvidas. Com Granada, tudo está claro, organizado e disponível quando você precisa.',
    'propietarios.cta_access': 'Solicitar Acesso',
    'propietarios.cta_agency': 'É uma Imobiliária?',
    
    // Proveedores page
    'proveedores.badge': 'Rede de Fornecedores',
    'proveedores.title': 'Rede de Fornecedores Confiáveis',
    'proveedores.subtitle': 'Conectamos imobiliárias com fornecedores verificados. Mais trabalho para profissionais, melhor serviço para as propriedades.',
    'proveedores.categories_title': 'Categorias de Serviços',
    'proveedores.categories_subtitle': 'Encontre o fornecedor certo para cada tipo de manutenção.',
    'proveedores.cat1_title': 'Encanamento',
    'proveedores.cat1_desc': 'Reparos, instalações e manutenção de sistemas hidráulicos',
    'proveedores.cat2_title': 'Elétrica',
    'proveedores.cat2_desc': 'Instalações elétricas, reparos e emergências',
    'proveedores.cat3_title': 'Pintura',
    'proveedores.cat3_desc': 'Pintura interna/externa, papel de parede e revestimentos',
    'proveedores.cat4_title': 'Limpeza',
    'proveedores.cat4_desc': 'Limpeza profunda, manutenção e desinfecção',
    'proveedores.cat5_title': 'Jardinagem',
    'proveedores.cat5_desc': 'Manutenção de áreas verdes e paisagismo',
    'proveedores.cat6_title': 'Chaveiro',
    'proveedores.cat6_desc': 'Troca de fechaduras, chaves e sistemas de segurança',
    'proveedores.benefits_title': 'Um Ecossistema que Beneficia a Todos',
    'proveedores.for_agencies': 'Para Imobiliárias',
    'proveedores.for_agencies_desc': 'Acesse fornecedores verificados e confiáveis. Cotize, aprove e acompanhe todos os trabalhos pelo Granada sem ligações nem mensagens.',
    'proveedores.agency_feature1': 'Fornecedores pré-verificados',
    'proveedores.agency_feature2': 'Comparação de orçamentos',
    'proveedores.agency_feature3': 'Acompanhamento em tempo real',
    'proveedores.agency_feature4': 'Histórico de trabalhos',
    'proveedores.for_providers': 'Para Fornecedores',
    'proveedores.for_providers_desc': 'Receba mais trabalho de imobiliárias profissionais. Gerencie pedidos, orçamentos e pagamentos de forma organizada.',
    'proveedores.provider_feature1': 'Acesso a múltiplas imobiliárias',
    'proveedores.provider_feature2': 'Agenda de trabalhos organizada',
    'proveedores.provider_feature3': 'Pagamentos seguros e pontuais',
    'proveedores.provider_feature4': 'Reputação verificável',
    'proveedores.how_title': 'Como Funciona o Sistema?',
    'proveedores.how_subtitle': 'Um processo simples e transparente para todos os envolvidos.',
    'proveedores.step1_title': 'Registro e Verificação',
    'proveedores.step1_desc': 'O fornecedor se registra com sua especialidade e documentação. Granada verifica credenciais e experiência.',
    'proveedores.step2_title': 'Solicitação de Orçamento',
    'proveedores.step2_desc': 'A imobiliária cadastra uma manutenção necessária. Os fornecedores da categoria recebem a notificação.',
    'proveedores.step3_title': 'Orçamento e Aprovação',
    'proveedores.step3_desc': 'O fornecedor envia orçamento. A imobiliária compara e aprova. O proprietário autoriza a despesa.',
    'proveedores.step4_title': 'Execução e Pagamento',
    'proveedores.step4_desc': 'O fornecedor executa o trabalho, envia fotos do resultado. O pagamento é processado através do Granada.',
    'proveedores.cta_title': 'Junte-se à Rede Granada',
    'proveedores.cta_subtitle': 'Você é um fornecedor de serviços para propriedades? Registre-se e acesse mais trabalho com imobiliárias profissionais que usam Granada.',
    'proveedores.cta_register': 'Registrar-se como Fornecedor',
    'proveedores.cta_directory': 'Ver Diretório de Fornecedores',
    
    // Planes page
    'planes.badge': 'Planos e Preços',
    'planes.title': 'Escolha o plano perfeito para seu negócio',
    'planes.subtitle': 'Planos flexíveis que se adaptam ao tamanho da sua carteira. Sem custos ocultos, sem compromissos de longo prazo.',
    'planes.billing_label': 'Assinatura com Pagamento',
    'planes.monthly': 'Mensal',
    'planes.yearly': 'Anual',
    'planes.off': 'OFF',
    'planes.equivalent': 'Equivalente a',
    'planes.per_month': '/mês',
    'planes.per_year': '/ano',
    'planes.start': 'Começar',
    'planes.contact': 'Contatar',
    'planes.popular': 'Mais Popular',
    'planes.faq_title': 'Perguntas Frequentes',
    'planes.cta_title': 'Pronto para começar?',
    'planes.cta_subtitle': 'Agende uma demo personalizada ou comece sua avaliação gratuita hoje.',
    'planes.cta_demo': 'Agendar Demo',
    'planes.cta_trial': 'Avaliação Gratuita',
    'planes.vat_note': 'Os valores expressos não incluem impostos',
    'planes.plan_basic': 'Básico',
    'planes.plan_professional': 'Profissional',
    'planes.plan_enterprise': 'Enterprise',
    'planes.plan_basic_desc': 'Plano ideal para pequenos proprietários ou administradores individuais',
    'planes.plan_professional_desc': 'Para imobiliárias ou administradoras médias com múltiplas propriedades',
    'planes.plan_enterprise_desc': 'Solução completa para grandes imobiliárias e corporativos',
    'planes.feature_properties': 'Até {n} propriedade',
    'planes.feature_properties_plural': 'Até {n} propriedades',
    'planes.feature_contracts': 'Até {n} contratos simultâneos',
    'planes.feature_users': '{n} usuários ativos',
    'planes.feature_branches': 'Até {n} filiais',
    'planes.feature_basic_reports': 'Relatórios básicos',
    'planes.feature_advanced_reports': 'Relatórios avançados',
    'planes.feature_advanced_reports_unlimited': 'Relatórios avançados ilimitados',
    'planes.feature_storage': '{n} GB armazenamento',
    'planes.feature_email_support': 'Suporte por email',
    'planes.feature_priority_support': 'Suporte prioritário',
    'planes.feature_priority_support_24': 'Suporte prioritário 24/7',
    'planes.feature_analytics': 'Analytics avançados',
    'planes.feature_analytics_bi': 'Analytics avançados com BI',
    'planes.feature_api': 'API access ({n} calls/dia)',
    'planes.feature_api_unlimited': 'API access ilimitado',
    'planes.feature_bulk': 'Operações em massa',
    'planes.feature_branding': 'Branding personalizado',
    'planes.feature_notifications': 'Notificações personalizadas',
    'planes.feature_whitelabel': 'Whitelabel (sem marca Granada)',
    'planes.request_plan': 'Solicitar Plano',
    'planes.faq1_q': 'Posso mudar de plano a qualquer momento?',
    'planes.faq1_a': 'Sim, você pode fazer upgrade ou downgrade do seu plano quando quiser. As mudanças se aplicam no próximo período de faturamento.',
    'planes.faq2_q': 'O que cada plano inclui?',
    'planes.faq2_a': 'Plano Básico: ideal para pequenos proprietários com até 1 propriedade e 2 contratos. Plano Profissional: para imobiliárias médias com até 5 propriedades, 10 contratos e funcionalidades avançadas. Plano Enterprise: solução completa com até 15 propriedades, 30 contratos e suporte prioritário 24/7.',
    'planes.faq3_q': 'Os preços incluem impostos?',
    'planes.faq3_a': 'Não, os preços mostrados não incluem impostos. O faturamento é mensal com todos os comprovantes fiscais correspondentes.',
    'planes.faq4_q': 'O que acontece se eu exceder o limite de propriedades ou contratos?',
    'planes.faq4_a': 'Avisamos quando você se aproximar do limite. Você pode fazer upgrade do seu plano a qualquer momento para continuar adicionando propriedades e contratos sem interrupções.',
    'planes.faq5_q': 'Como funciona o suporte técnico?',
    'planes.faq5_a': 'Plano Básico: suporte por email. Plano Profissional: suporte por email com prioridade. Plano Enterprise: suporte prioritário 24/7 com atendimento personalizado.',
    
    // Contacto page
    'contacto.badge': 'Contato',
    'contacto.title': 'Como podemos ajudar?',
    'contacto.subtitle': 'Estamos aqui para responder suas perguntas sobre Granada Platform',
    'contacto.form_title': 'Envie-nos uma mensagem',
    'contacto.info_title': 'Outras formas de contato',
    'contacto.email': 'Email',
    'contacto.email_desc': 'Escreva-nos e responderemos em breve',
    'contacto.phone': 'Telefone',
    'contacto.phone_desc': 'Ligue-nos em horário comercial',
    'contacto.office': 'Escritório',
    'contacto.office_desc': 'Visite-nos em nossa localização',
    'contacto.hours': 'Horários',
    'contacto.hours_desc': 'Estamos disponíveis',
    'contacto.hours_weekdays': 'Segunda a Sexta: 9:00 - 18:00',
    'contacto.hours_saturday': 'Sábado: 9:00 - 13:00',
    'contacto.toast_success': 'Mensagem enviada!',
    'contacto.toast_success_desc': 'Entraremos em contato nas próximas 24-48 horas.',
    'contacto.toast_error': 'Erro',
    'contacto.toast_error_desc': 'Não foi possível enviar a mensagem. Tente novamente.',
    
    // Footer
    'footer.rights': 'Todos os direitos reservados',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Serviço',
    
    // Final CTA Section
    'cta.title': 'Pronto para transformar sua gestão imobiliária?',
    'cta.subtitle': 'Junte-se às imobiliárias que já confiam no Granada para simplificar suas operações diárias.',
    'cta.card1_title': 'Imobiliárias e Administradores',
    'cta.card1_desc': 'Descubra como o Granada pode otimizar sua gestão de propriedades.',
    'cta.card1_button': 'Ver Soluções',
    'cta.card2_title': 'Proprietários',
    'cta.card2_desc': 'Mantenha o controle de seus investimentos com relatórios automáticos.',
    'cta.card2_button': 'Saiba Mais',
    'cta.card3_title': 'Tem Dúvidas?',
    'cta.card3_desc': 'Nossa equipe está pronta para ajudá-lo.',
    'cta.card3_button': 'Contatar',
    
    // Lifecycle Section
    'lifecycle.title': 'Do anúncio à renovação do contrato, em uma única plataforma',
    'lifecycle.subtitle': 'Granada organiza a relação entre Proprietário, Propriedade, Inquilino, Contrato, Assinaturas, Pagamentos, Cobranças, Renovações e Fornecedores. Um fluxo claro, sem depender de 20 planilhas e 15 grupos de WhatsApp.',
    'lifecycle.step1_title': 'Captar e preparar a propriedade',
    'lifecycle.step1_desc': 'Carregue a propriedade com dados chave: localização, tipo de aluguel, valor, moeda, inventário, fotos, documentação. Defina Proprietário, Imobiliária/Administrador e distribuição de fundos.',
    'lifecycle.step2_title': 'Publicação e seleção de inquilino',
    'lifecycle.step2_desc': 'Integre Granada com portais, receba interessados, registre candidatos, requisitos e decisões. Todo o contexto no sistema.',
    'lifecycle.step3_title': 'Contrato e assinaturas',
    'lifecycle.step3_desc': 'Gere o contrato a partir do Granada com todos os dados chave. Gerencie assinaturas digitais ou presenciais, tudo documentado.',
    'lifecycle.step4_title': 'Pagamentos e cobranças mensais',
    'lifecycle.step4_desc': 'Granada calcula valores, gera lembretes, registra pagamentos/atrasos, distribui valores segundo honorários, comissões, retenções.',
    'lifecycle.step5_title': 'Despesas, manutenções e fornecedores',
    'lifecycle.step5_desc': 'Crie ordens de trabalho, atribua fornecedores, registre orçamentos. O proprietário aprova e tudo fica associado.',
    'lifecycle.step6_title': 'Relatórios e relação com o proprietário',
    'lifecycle.step6_desc': 'Todo mês: relatório claro de aluguéis, despesas, comissões e saldo líquido. Portal do Proprietário para mais detalhes.',
    'lifecycle.step7_title': 'Renovações, atualizações e encerramento',
    'lifecycle.step7_desc': 'Granada avisa vencimentos, opções de renovação, índices de atualização. Todo o histórico disponível.',
    
    // Role Views Section
    'roles.title': 'Uma visão para cada papel',
    'roles.admin_title': 'Imobiliária / Administrador',
    'roles.admin_desc': 'Painel global, KPIs de cobranças/despesas/rentabilidade, gestão de renovações e fornecedores',
    'roles.admin_feature1': 'Dashboard com métricas chave',
    'roles.admin_feature2': 'Gestão de múltiplas propriedades',
    'roles.admin_feature3': 'Controle de vencimentos',
    'roles.admin_feature4': 'Coordenação de fornecedores',
    'roles.owner_title': 'Proprietário',
    'roles.owner_desc': 'Resumos mensais, contratos e vencimentos, histórico de cobranças e despesas',
    'roles.owner_feature1': 'Relatórios mensais automáticos',
    'roles.owner_feature2': 'Visibilidade total de receitas/despesas',
    'roles.owner_feature3': 'Histórico completo por propriedade',
    'roles.owner_feature4': 'Aprovação de despesas extraordinárias',
    'roles.tenant_title': 'Inquilino',
    'roles.tenant_desc': 'Contrato e pagamentos em um só lugar, lembretes, canal para reportar problemas',
    'roles.tenant_feature1': 'Acesso ao contrato digital',
    'roles.tenant_feature2': 'Histórico de pagamentos',
    'roles.tenant_feature3': 'Lembretes automáticos',
    'roles.tenant_feature4': 'Reporte de manutenções',
  }
};

const GranadaLanguageContext = createContext<GranadaLanguageContextType | undefined>(undefined);

export function GranadaLanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<GranadaLanguage>(() => {
    const saved = localStorage.getItem('granada-language');
    return (saved as GranadaLanguage) || 'es';
  });

  useEffect(() => {
    localStorage.setItem('granada-language', language);
  }, [language]);

  const setLanguage = (lang: GranadaLanguage) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <GranadaLanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </GranadaLanguageContext.Provider>
  );
}

export function useGranadaLanguage() {
  const context = useContext(GranadaLanguageContext);
  if (context === undefined) {
    throw new Error('useGranadaLanguage must be used within a GranadaLanguageProvider');
  }
  return context;
}
