import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.industries': 'Industries & Programs',
    'nav.financing': 'Financing',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.getStarted': 'Get Started',
    
    // Home page
    'home.hero.badge': 'Real Estate Excellence',
    'home.hero.title': 'Welcome to WM Management & Investments',
    'home.hero.subtitle': 'At WM, we transform complexity into clarity. We are passionate about embracing your visions and challenges, transforming the way we live, work, and develop our communities.',
    'home.hero.description': 'Our experienced team and digital solutions turn intricate real estate challenges into straightforward, actionable opportunities with measurable success.',
    'home.hero.cta1': 'Explore Our Services',
    'home.hero.cta2': 'Discover Financing Solutions',
    'home.hero.feature1': 'Property Management Excellence',
    'home.hero.feature2': 'Strategic Investment Solutions',
    'home.hero.feature3': 'Real Estate Development',
    'home.hero.feature4': 'Expert Consulting Services',
    'home.services.title': 'Integrated Solutions for Real Estate Success',
    'home.services.subtitle': 'From property management to investment trust services, we deliver clarity and results across every aspect of real estate.',
    'home.services.property.title': 'Property Management',
    'home.services.property.description': 'Comprehensive property care from lease administration to strategic optimization.',
    'home.services.brokerage.title': 'Brokerage',
    'home.services.brokerage.description': 'Expert guidance connecting opportunities with precision and transparency.',
    'home.services.consulting.title': 'Consulting Services',
    'home.services.consulting.description': 'Strategic insights that transform complex challenges into clear opportunities.',
    'home.services.development.title': 'Real Estate Development',
    'home.services.development.description': 'From vision to reality—comprehensive development management and execution.',
    'home.services.investments.title': 'Trust & Investments',
    'home.services.investments.description': 'Secure, transparent investment frameworks with risk-adjusted returns.',
    'home.services.financing.title': 'Financing Solutions',
    'home.services.financing.description': 'Competitive financing with interest-free options for your remodeling projects.',
    'home.news.title': 'Latest News & Updates',
    'home.news.content': 'Stay informed about the latest trends, opportunities, and insights in real estate. Our team regularly shares market updates, investment tips, and industry expertise to help you make informed decisions.',
    'home.learnMore': 'Learn More',
    'home.simulator.cta': 'Try Our Simulator',

    // About page
    'about.hero.badge': 'Our Story',
    'about.hero.title': 'Transforming Real Estate Excellence',
    'about.hero.subtitle': 'With decades of combined experience and a passion for innovation, we help clients navigate the complex world of real estate with confidence and clarity.',
    'about.mission.title': 'Our Mission',
    'about.mission.content1': 'At WM Management & Investments, we believe in transforming complexity into clarity. Our mission is to provide comprehensive real estate solutions that empower our clients to make informed decisions and achieve their investment goals.',
    'about.mission.content2': 'We combine deep market knowledge with innovative technology to deliver transparent, efficient, and personalized service across all our business lines.',
    'about.vision.title': 'Our Vision',
    'about.vision.content': 'To be the leading real estate management and investment firm, recognized for our integrity, innovation, and unwavering commitment to client success. We envision a future where every real estate transaction is transparent, efficient, and profitable for all parties involved.',
    'about.news.title': 'Latest Company Updates',
    'about.news.subtitle': 'Stay informed about our growth',
    'about.news.content': 'We are continuously expanding our services and capabilities to better serve our clients. From new technology implementations to strategic partnerships, we keep our stakeholders informed about our progress and future plans.',
    'about.team.title': 'Our Team',
    'about.team.subtitle': 'Meet the professionals dedicated to your success. Our diverse team brings together expertise in real estate, finance, technology, and client relations.',
    'about.team.leadership': 'Leadership Team',
    'about.team.leadership.desc': 'Experienced executives with proven track records in real estate development, investment management, and strategic business growth.',
    'about.team.strategy': 'Strategic Planning',
    'about.team.strategy.desc': 'Market analysts and strategic planners who identify opportunities and develop comprehensive investment strategies for optimal returns.',
    'about.team.client': 'Client Relations',
    'about.team.client.desc': 'Dedicated professionals focused on understanding client needs and providing personalized service throughout every transaction and partnership.',
    'about.expansion.title': 'Expansion & Growth',
    'about.expansion.subtitle': 'Building for the future',
    'about.expansion.content': 'We are actively expanding our geographic reach and service offerings to meet the evolving needs of our clients. Our growth strategy focuses on sustainable expansion while maintaining our commitment to quality and personal service.',
    'about.values.title': 'Our Core Values',
    'about.values.subtitle': 'The principles that guide everything we do',
    'about.values.transparency': 'Transparency',
    'about.values.transparency.desc': 'We believe in open, honest communication and provide clear, detailed information about all our services and processes.',
    'about.values.integrity': 'Integrity',
    'about.values.integrity.desc': 'We conduct business with the highest ethical standards and always act in our clients\' best interests.',
    'about.values.excellence': 'Excellence',
    'about.values.excellence.desc': 'We strive for exceptional quality in every aspect of our service, continuously improving and innovating to exceed expectations.',

    // Common
    'common.readyToStart': 'Ready to Get Started?',
    'common.contactTeam': 'Contact Our Team',
    'common.keyFeatures': 'Key Features:',
    'common.language': 'Language',
    'common.trySimulator': 'Try Our Simulator',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.learnMore': 'Learn More',
    'common.contactUs': 'Contact Us',
    'common.phone': 'Phone',
    'common.email': 'Email',
    'common.address': 'Address',
    'common.name': 'Name',
    'common.message': 'Message',
    'common.send': 'Send',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.open': 'Open',

    // Investment Simulator
    'simulator.title': 'Business Investment Plan Simulator',
    'simulator.description': 'Plan your franchise investment with our interactive tool. Adjust variables to see real-time projections of costs and financing options.',
    'simulator.tabs.basic': 'Basic Configuration',
    'simulator.tabs.advanced': 'Advanced Configuration',
    'simulator.tabs.results': 'Results & Analysis',
    'simulator.totalCost.title': 'Total Franchise Cost',
    'simulator.totalCost.description': 'Enter the total investment required for the franchise',
    'simulator.totalCost.label': 'Total Cost ($)',
    'simulator.breakdown.title': 'Cost Breakdown Percentages',
    'simulator.breakdown.description': 'Adjust your total investment allocation',
    'simulator.breakdown.entranceFee': 'Entrance Fee',
    'simulator.breakdown.infrastructure': 'Infrastructure & Renovation',
    'simulator.breakdown.equipment': 'Equipment & Assets',
    'simulator.breakdown.workingCapital': 'Working Capital',
    'simulator.financing.title': 'Financing Details',
    'simulator.financing.description': 'Configure your financing options for infrastructure costs',
    'simulator.financing.percentage': 'Financed Percentage',
    'simulator.financing.term': 'Financing Term (months)',
    'simulator.financing.rate': 'Interest Rate (%)',
    'simulator.property.title': 'Property Details',
    'simulator.property.description': 'Specific details about your franchise location',
    'simulator.property.size': 'Property Size (m²)',
    'simulator.property.costM2': 'Cost per m² ($)',
    'simulator.property.insurance': 'Insurance Cost ($)',
    'simulator.results.costBreakdown': 'Cost Breakdown',
    'simulator.results.costBreakdown.desc': 'Visual representation of your investment allocation',
    'simulator.results.financingBreakdown': 'Financing Breakdown',
    'simulator.results.financingBreakdown.desc': 'Infrastructure financing vs out-of-pocket costs',
    'simulator.results.summary': 'Financial Summary',
    'simulator.results.summary.desc': 'Complete breakdown of your franchise investment',
    'simulator.results.totalInvestment': 'Total Investment',
    'simulator.results.upfrontPayment': 'Upfront Payment',
    'simulator.results.financedAmount': 'Financed Amount',
    'simulator.results.monthlyPayment': 'Monthly Payment',
    'simulator.results.detailedBreakdown': 'Detailed Breakdown:',
    'simulator.results.save': 'Save Scenario',
    'simulator.results.export': 'Export Report',
    'simulator.chart.financed': 'Financed',
    'simulator.chart.outOfPocket': 'Out of Pocket',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Quiénes Somos',
    'nav.services': 'Servicios',
    'nav.industries': 'Industrias y Programas',
    'nav.financing': 'Financiamiento',
    'nav.contact': 'Contacto',
    'nav.faq': 'Preguntas Frecuentes',
    'nav.getStarted': 'Comenzar',
    
    // Home page
    'home.hero.badge': 'Excelencia Inmobiliaria',
    'home.hero.title': 'Bienvenido a WM Management & Investments',
    'home.hero.subtitle': 'En WM, transformamos la complejidad en claridad. Nos apasiona abrazar sus visiones y desafíos, transformando la forma en que vivimos, trabajamos y desarrollamos nuestras comunidades.',
    'home.hero.description': 'Nuestro equipo experimentado y soluciones digitales convierten los complejos desafíos inmobiliarios en oportunidades claras y accionables con éxito medible.',
    'home.hero.cta1': 'Explorar Nuestros Servicios',
    'home.hero.cta2': 'Descubrir Soluciones de Financiamiento',
    'home.hero.feature1': 'Excelencia en Administración de Propiedades',
    'home.hero.feature2': 'Soluciones Estratégicas de Inversión',
    'home.hero.feature3': 'Desarrollo Inmobiliario',
    'home.hero.feature4': 'Servicios Expertos de Consultoría',
    'home.services.title': 'Soluciones Integradas para el Éxito Inmobiliario',
    'home.services.subtitle': 'Desde administración de propiedades hasta servicios de fideicomiso de inversión, entregamos claridad y resultados en todos los aspectos del sector inmobiliario.',
    'home.services.property.title': 'Administración de Propiedades',
    'home.services.property.description': 'Cuidado integral de propiedades desde administración de arrendamientos hasta optimización estratégica.',
    'home.services.brokerage.title': 'Corretaje',
    'home.services.brokerage.description': 'Orientación experta conectando oportunidades con precisión y transparencia.',
    'home.services.consulting.title': 'Servicios de Consultoría',
    'home.services.consulting.description': 'Perspectivas estratégicas que transforman desafíos complejos en oportunidades claras.',
    'home.services.development.title': 'Desarrollo Inmobiliario',
    'home.services.development.description': 'De la visión a la realidad: gestión y ejecución integral de desarrollo.',
    'home.services.investments.title': 'Fideicomiso e Inversiones',
    'home.services.investments.description': 'Marcos de inversión seguros y transparentes con retornos ajustados al riesgo.',
    'home.services.financing.title': 'Soluciones de Financiamiento',
    'home.services.financing.description': 'Financiamiento competitivo con opciones sin intereses para sus proyectos de remodelación.',
    'home.news.title': 'Últimas Noticias y Actualizaciones',
    'home.news.content': 'Manténgase informado sobre las últimas tendencias, oportunidades e insights en el sector inmobiliario. Nuestro equipo comparte regularmente actualizaciones del mercado, consejos de inversión y experiencia de la industria para ayudarle a tomar decisiones informadas.',
    'home.learnMore': 'Saber Más',
    'home.simulator.cta': 'Probar Nuestro Simulador',

    // About page
    'about.hero.badge': 'Nuestra Historia',
    'about.hero.title': 'Transformando la Excelencia Inmobiliaria',
    'about.hero.subtitle': 'Con décadas de experiencia combinada y pasión por la innovación, ayudamos a los clientes a navegar el complejo mundo de los bienes raíces con confianza y claridad.',
    'about.mission.title': 'Nuestra Misión',
    'about.mission.content1': 'En WM Management & Investments, creemos en transformar la complejidad en claridad. Nuestra misión es proporcionar soluciones inmobiliarias integrales que empoderen a nuestros clientes para tomar decisiones informadas y alcanzar sus objetivos de inversión.',
    'about.mission.content2': 'Combinamos conocimiento profundo del mercado con tecnología innovadora para entregar servicios transparentes, eficientes y personalizados en todas nuestras líneas de negocio.',
    'about.vision.title': 'Nuestra Visión',
    'about.vision.content': 'Ser la empresa líder en administración e inversión inmobiliaria, reconocida por nuestra integridad, innovación y compromiso inquebrantable con el éxito del cliente. Visualizamos un futuro donde cada transacción inmobiliaria sea transparente, eficiente y rentable para todas las partes involucradas.',
    'about.news.title': 'Últimas Actualizaciones de la Empresa',
    'about.news.subtitle': 'Manténgase informado sobre nuestro crecimiento',
    'about.news.content': 'Estamos expandiendo continuamente nuestros servicios y capacidades para servir mejor a nuestros clientes. Desde nuevas implementaciones tecnológicas hasta alianzas estratégicas, mantenemos informados a nuestros stakeholders sobre nuestro progreso y planes futuros.',
    'about.team.title': 'Nuestro Equipo',
    'about.team.subtitle': 'Conozca a los profesionales dedicados a su éxito. Nuestro equipo diverso reúne experiencia en bienes raíces, finanzas, tecnología y relaciones con clientes.',
    'about.team.leadership': 'Equipo de Liderazgo',
    'about.team.leadership.desc': 'Ejecutivos experimentados con historiales comprobados en desarrollo inmobiliario, gestión de inversiones y crecimiento empresarial estratégico.',
    'about.team.strategy': 'Planificación Estratégica',
    'about.team.strategy.desc': 'Analistas de mercado y planificadores estratégicos que identifican oportunidades y desarrollan estrategias de inversión integrales para retornos óptimos.',
    'about.team.client': 'Relaciones con Clientes',
    'about.team.client.desc': 'Profesionales dedicados enfocados en entender las necesidades del cliente y brindar servicio personalizado durante cada transacción y asociación.',
    'about.expansion.title': 'Expansión y Crecimiento',
    'about.expansion.subtitle': 'Construyendo para el futuro',
    'about.expansion.content': 'Estamos expandiendo activamente nuestro alcance geográfico y ofertas de servicios para satisfacer las necesidades cambiantes de nuestros clientes. Nuestra estrategia de crecimiento se enfoca en expansión sostenible mientras mantenemos nuestro compromiso con la calidad y el servicio personal.',
    'about.values.title': 'Nuestros Valores Fundamentales',
    'about.values.subtitle': 'Los principios que guían todo lo que hacemos',
    'about.values.transparency': 'Transparencia',
    'about.values.transparency.desc': 'Creemos en la comunicación abierta y honesta y proporcionamos información clara y detallada sobre todos nuestros servicios y procesos.',
    'about.values.integrity': 'Integridad',
    'about.values.integrity.desc': 'Conducimos nuestro negocio con los más altos estándares éticos y siempre actuamos en el mejor interés de nuestros clientes.',
    'about.values.excellence': 'Excelencia',
    'about.values.excellence.desc': 'Nos esforzamos por la calidad excepcional en todos los aspectos de nuestro servicio, mejorando continuamente e innovando para superar las expectativas.',

    // Common
    'common.readyToStart': '¿Listo para Comenzar?',
    'common.contactTeam': 'Contactar Nuestro Equipo',
    'common.keyFeatures': 'Características Clave:',
    'common.language': 'Idioma',
    'common.trySimulator': 'Probar Nuestro Simulador',
    'common.submit': 'Enviar',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.required': 'Requerido',
    'common.optional': 'Opcional',
    'common.learnMore': 'Saber Más',
    'common.contactUs': 'Contáctenos',
    'common.phone': 'Teléfono',
    'common.email': 'Correo Electrónico',
    'common.address': 'Dirección',
    'common.name': 'Nombre',
    'common.message': 'Mensaje',
    'common.send': 'Enviar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.close': 'Cerrar',
    'common.open': 'Abrir',

    // Investment Simulator
    'simulator.title': 'Simulador de Plan de Inversión de Negocio',
    'simulator.description': 'Planifique su inversión de franquicia con nuestra herramienta interactiva. Ajuste variables para ver proyecciones en tiempo real de costos y opciones de financiamiento.',
    'simulator.tabs.basic': 'Configuración Básica',
    'simulator.tabs.advanced': 'Configuración Avanzada',
    'simulator.tabs.results': 'Resultados y Análisis',
    'simulator.totalCost.title': 'Costo Total de Franquicia',
    'simulator.totalCost.description': 'Ingrese la inversión total requerida para la franquicia',
    'simulator.totalCost.label': 'Costo Total ($)',
    'simulator.breakdown.title': 'Porcentajes de Desglose de Costos',
    'simulator.breakdown.description': 'Ajuste la asignación de su inversión total',
    'simulator.breakdown.entranceFee': 'Cuota de Entrada',
    'simulator.breakdown.infrastructure': 'Infraestructura y Remodelación',
    'simulator.breakdown.equipment': 'Equipos y Activos',
    'simulator.breakdown.workingCapital': 'Capital de Trabajo',
    'simulator.financing.title': 'Detalles de Financiamiento',
    'simulator.financing.description': 'Configure sus opciones de financiamiento para costos de infraestructura',
    'simulator.financing.percentage': 'Porcentaje Financiado',
    'simulator.financing.term': 'Plazo de Financiamiento (meses)',
    'simulator.financing.rate': 'Tasa de Interés (%)',
    'simulator.property.title': 'Detalles de la Propiedad',
    'simulator.property.description': 'Detalles específicos sobre la ubicación de su franquicia',
    'simulator.property.size': 'Tamaño del Local (m²)',
    'simulator.property.costM2': 'Costo por m² ($)',
    'simulator.property.insurance': 'Costo de Seguro ($)',
    'simulator.results.costBreakdown': 'Desglose de Costos',
    'simulator.results.costBreakdown.desc': 'Representación visual de la asignación de su inversión',
    'simulator.results.financingBreakdown': 'Desglose de Financiamiento',
    'simulator.results.financingBreakdown.desc': 'Financiamiento de infraestructura vs costos de bolsillo',
    'simulator.results.summary': 'Resumen Financiero',
    'simulator.results.summary.desc': 'Desglose completo de su inversión de franquicia',
    'simulator.results.totalInvestment': 'Inversión Total',
    'simulator.results.upfrontPayment': 'Pago Inicial',
    'simulator.results.financedAmount': 'Monto Financiado',
    'simulator.results.monthlyPayment': 'Pago Mensual',
    'simulator.results.detailedBreakdown': 'Desglose Detallado:',
    'simulator.results.save': 'Guardar Escenario',
    'simulator.results.export': 'Exportar Reporte',
    'simulator.chart.financed': 'Financiado',
    'simulator.chart.outOfPocket': 'De su Bolsillo',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
