import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.industries': 'Industries & Programs',
    'nav.financing': 'Financing',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.getStarted': 'Get Started',
    
    // Home page
    'home.hero.badge': 'Real Estate Excellence',
    'home.hero.title': 'Welcome to WM Management & Investments',
    'home.hero.subtitle': 'At WM, we transform complexity into clarity. We are passionate about embracing your visions and challenges, transforming the way we live, work, and develop our communities.',
    'home.hero.description': 'Our experienced team and digital solutions turn intricate real estate challenges into straightforward, actionable opportunities with measurable success.',
    'home.hero.cta1': 'Explore Our Services',
    'home.hero.cta2': 'Discover Financing Solutions',
    'home.hero.feature1': 'Property Management Excellence',
    'home.hero.feature2': 'Strategic Investment Solutions',
    'home.hero.feature3': 'Real Estate Development',
    'home.hero.feature4': 'Expert Consulting Services',
    'home.services.title': 'Integrated Solutions for Real Estate Success',
    'home.services.subtitle': 'From property management to investment trust services, we deliver clarity and results across every aspect of real estate.',
    'home.services.property.title': 'Property Management',
    'home.services.property.description': 'Comprehensive property care from lease administration to strategic optimization.',
    'home.services.brokerage.title': 'Brokerage',
    'home.services.brokerage.description': 'Expert guidance connecting opportunities with precision and transparency.',
    'home.services.consulting.title': 'Consulting Services',
    'home.services.consulting.description': 'Strategic insights that transform complex challenges into clear opportunities.',
    'home.services.development.title': 'Real Estate Development',
    'home.services.development.description': 'From vision to reality—comprehensive development management and execution.',
    'home.services.investments.title': 'Trust & Investments',
    'home.services.investments.description': 'Secure, transparent investment frameworks with risk-adjusted returns.',
    'home.services.financing.title': 'Financing Solutions',
    'home.services.financing.description': 'Competitive financing with interest-free options for your remodeling projects.',
    'home.news.title': 'Latest News & Updates',
    'home.news.content': 'Stay informed about the latest trends, opportunities, and insights in real estate. Our team regularly shares market updates, investment tips, and industry expertise to help you make informed decisions.',
    'home.learnMore': 'Learn More',
    'home.simulator.cta': 'Try Our Simulator',

    // About page
    'about.hero.badge': 'Our Story',
    'about.hero.title': 'Transforming Real Estate Excellence',
    'about.hero.subtitle': 'With decades of combined experience and a passion for innovation, we help clients navigate the complex world of real estate with confidence and clarity.',
    'about.mission.title': 'Our Mission',
    'about.mission.content1': 'At WM Management & Investments, we believe in transforming complexity into clarity. Our mission is to provide comprehensive real estate solutions that empower our clients to make informed decisions and achieve their investment goals.',
    'about.mission.content2': 'We combine deep market knowledge with innovative technology to deliver transparent, efficient, and personalized service across all our business lines.',
    'about.vision.title': 'Our Vision',
    'about.vision.content': 'To be the leading real estate management and investment firm, recognized for our integrity, innovation, and unwavering commitment to client success. We envision a future where every real estate transaction is transparent, efficient, and profitable for all parties involved.',
    'about.news.title': 'Latest Company Updates',
    'about.news.subtitle': 'Stay informed about our growth',
    'about.news.content': 'We are continuously expanding our services and capabilities to better serve our clients. From new technology implementations to strategic partnerships, we keep our stakeholders informed about our progress and future plans.',
    'about.team.title': 'Our Team',
    'about.team.subtitle': 'Meet the professionals dedicated to your success. Our diverse team brings together expertise in real estate, finance, technology, and client relations.',
    'about.team.leadership': 'Leadership Team',
    'about.team.leadership.desc': 'Experienced executives with proven track records in real estate development, investment management, and strategic business growth.',
    'about.team.strategy': 'Strategic Planning',
    'about.team.strategy.desc': 'Market analysts and strategic planners who identify opportunities and develop comprehensive investment strategies for optimal returns.',
    'about.team.client': 'Client Relations',
    'about.team.client.desc': 'Dedicated professionals focused on understanding client needs and providing personalized service throughout every transaction and partnership.',
    'about.expansion.title': 'Expansion & Growth',
    'about.expansion.subtitle': 'Building for the future',
    'about.expansion.content': 'We are actively expanding our geographic reach and service offerings to meet the evolving needs of our clients. Our growth strategy focuses on sustainable expansion while maintaining our commitment to quality and personal service.',
    'about.values.title': 'Our Core Values',
    'about.values.subtitle': 'The principles that guide everything we do',
    'about.values.transparency': 'Transparency',
    'about.values.transparency.desc': 'We believe in open, honest communication and provide clear, detailed information about all our services and processes.',
    'about.values.integrity': 'Integrity',
    'about.values.integrity.desc': 'We conduct business with the highest ethical standards and always act in our clients\' best interests.',
    'about.values.excellence': 'Excellence',
    'about.values.excellence.desc': 'We strive for exceptional quality in every aspect of our service, continuously improving and innovating to exceed expectations.',

    // Services page
    'services.hero.badge': 'Our Services',
    'services.hero.title': 'Comprehensive Real Estate Solutions',
    'services.hero.subtitle': 'From property management to strategic consulting, we provide end-to-end services designed to maximize your real estate investments and streamline your operations.',
    'services.property.title': 'Property Management',
    'services.property.description': 'Our comprehensive property management services ensure your investments are well-maintained, profitable, and compliant with all regulations while providing exceptional tenant experiences.',
    'services.property.features.lease': 'Lease Administration',
    'services.property.features.maintenance': 'Maintenance Coordination',
    'services.property.features.performance': 'Performance Analytics',
    'services.property.features.reporting': 'Financial Reporting',
    'services.property.cta': 'Learn More About Property Management',
    'services.brokerage.title': 'Real Estate Brokerage',
    'services.brokerage.description': 'Expert brokerage services connecting buyers and sellers with precision, transparency, and deep market knowledge to ensure successful transactions for all parties.',
    'services.brokerage.features.analysis': 'Market Analysis',
    'services.brokerage.features.transaction': 'Transaction Management',
    'services.brokerage.features.negotiations': 'Expert Negotiations',
    'services.brokerage.features.diligence': 'Due Diligence',
    'services.brokerage.cta': 'Explore Brokerage Services',
    'services.consulting.title': 'Strategic Consulting',
    'services.consulting.description': 'Strategic insights and expert guidance to help you navigate complex real estate decisions, optimize portfolios, and identify new investment opportunities.',
    'services.consulting.features.feasibility': 'Feasibility Studies',
    'services.consulting.features.legal': 'Legal Compliance',
    'services.consulting.features.planning': 'Strategic Planning',
    'services.consulting.features.research': 'Market Research',
    'services.consulting.cta': 'Get Strategic Consulting',
    'services.development.title': 'Real Estate Development',
    'services.development.description': 'From vision to reality, we manage every aspect of real estate development projects, ensuring quality execution, timeline adherence, and budget optimization.',
    'services.development.features.project': 'Project Management',
    'services.development.features.design': 'Design Coordination',
    'services.development.features.construction': 'Construction Oversight',
    'services.development.features.quality': 'Quality Assurance',
    'services.development.cta': 'Start Development Project',
    'services.investments.title': 'Trust & Investment Services',
    'services.investments.description': 'Secure and transparent investment frameworks designed to provide consistent returns while minimizing risk through diversified real estate portfolios.',
    'services.investments.features.portfolio': 'Portfolio Management',
    'services.investments.features.risk': 'Risk Assessment',
    'services.investments.features.strategy': 'Investment Strategy',
    'services.investments.features.monitoring': 'Performance Monitoring',
    'services.investments.cta': 'Explore Investment Options',
    'services.card.description': 'Professional {service} services tailored to your specific needs and goals.',
    'services.news.title': 'Service Updates & Innovations',
    'services.news.subtitle': 'Staying ahead with new capabilities',
    'services.news.content': 'We continuously enhance our service offerings with new technologies, expanded capabilities, and innovative solutions to better serve our clients evolving needs.',
    'services.cta.description': 'Ready to transform your real estate experience? Contact us today to discuss how our comprehensive services can help you achieve your goals.',

    // Industries page
    'industries.hero.badge': 'Industries & Programs',
    'industries.hero.title': 'Specialized Solutions by Industry',
    'industries.hero.subtitle': 'We provide tailored real estate solutions for diverse industries, understanding the unique requirements and challenges of each sector to deliver optimal results.',
    'industries.overview.title': 'Industry Expertise Across Sectors',
    'industries.overview.subtitle': 'Comprehensive understanding of industry-specific needs and regulations',
    'industries.overview.description': 'Our deep industry knowledge enables us to provide specialized services that address the unique challenges and opportunities within each sector. From compliance requirements to operational needs, we deliver solutions that drive success.',
    'industries.sectors.title': 'Industry Sectors We Serve',
    'industries.sectors.subtitle': 'Specialized expertise across multiple industries',
    'industries.residential.title': 'Residential Real Estate',
    'industries.residential.description': 'Comprehensive residential property solutions including single-family homes, condominiums, and multi-family developments with focus on community building and resident satisfaction.',
    'industries.residential.cta': 'Explore Residential Services',
    'industries.commercial.title': 'Commercial Properties',
    'industries.commercial.description': 'Strategic commercial real estate services for office buildings, retail spaces, and mixed-use developments that maximize value and operational efficiency.',
    'industries.commercial.cta': 'Learn About Commercial Solutions',
    'industries.health.title': 'Healthcare Facilities',
    'industries.health.description': 'Specialized healthcare real estate services ensuring compliance with medical facility regulations while optimizing patient care environments and operational workflows.',
    'industries.health.cta': 'Healthcare Real Estate Solutions',
    'industries.industrial.title': 'Industrial Properties',
    'industries.industrial.description': 'Expert management of industrial facilities, manufacturing plants, and distribution centers with focus on operational efficiency and safety compliance.',
    'industries.industrial.cta': 'Industrial Property Services',
    'industries.logistics.title': 'Logistics & Warehousing',
    'industries.logistics.description': 'Specialized logistics real estate solutions for warehouses, distribution centers, and supply chain facilities optimized for modern commerce demands.',
    'industries.logistics.cta': 'Logistics Real Estate Services',
    'industries.governments.title': 'Government & Public Sector',
    'industries.governments.description': 'Public sector real estate services with deep understanding of government regulations, procurement processes, and community development requirements.',
    'industries.governments.cta': 'Government Services',
    'industries.stats.title': 'Our Industry Impact',
    'industries.stats.subtitle': 'Delivering results across all sectors',
    'industries.stats.projects': 'Completed Projects',
    'industries.stats.clients': 'Industry Clients',
    'industries.stats.years': 'Years of Experience',
    'industries.news.title': 'Industry Insights & Updates',
    'industries.news.subtitle': 'Staying ahead of industry trends',
    'industries.news.content': 'We continuously monitor industry trends, regulatory changes, and market developments to ensure our clients stay ahead of the curve and capitalize on emerging opportunities.',

    // Common
    'common.readyToStart': 'Ready to Get Started?',
    'common.contactTeam': 'Contact Our Team',
    'common.keyFeatures': 'Key Features:',
    'common.language': 'Language',
    'common.trySimulator': 'Try Our Simulator',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.learnMore': 'Learn More',
    'common.contactUs': 'Contact Us',
    'common.phone': 'Phone',
    'common.email': 'Email',
    'common.address': 'Address',
    'common.name': 'Name',
    'common.message': 'Message',
    'common.send': 'Send',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.open': 'Open',

    // Financing
    'financing.hero.badge': 'Franchise Financing',
    'financing.hero.title': 'Flexible Financing Solutions for Your Business',
    'financing.hero.subtitle': 'Access the capital you need to start your franchise with our comprehensive financing programs designed for success.',
    'financing.program.title': 'Our Financing Program',
    'financing.program.description1': 'We understand that starting a franchise requires significant capital investment. Our specialized financing solutions are designed to help entrepreneurs access the funding they need to launch and grow their business.',
    'financing.program.description2': 'With competitive rates, flexible terms, and quick approval processes, we make it easier for qualified candidates to secure the financing needed for their franchise investment.',
    'financing.program.features.interest': 'Competitive Interest Rates',
    'financing.program.features.interest.desc': 'Benefit from competitive interest rates that make your financing affordable and manageable.',
    'financing.program.features.terms': 'Flexible Terms',
    'financing.program.features.terms.desc': 'Choose from various term options that align with your business cash flow and growth projections.',
    'financing.program.features.secure': 'Secure Process',
    'financing.program.features.secure.desc': 'Our secure application and approval process protects your information while expediting your financing.',
    'financing.program.features.coverage': 'Comprehensive Coverage',
    'financing.program.features.coverage.desc': 'Finance up to 80% of your total franchise investment, including equipment, renovation, and working capital.',
    'financing.program.cta': 'Apply for Financing',
    'financing.program.benefits.title': 'Program Benefits',
    'financing.program.benefits.subtitle': 'Why choose our financing solution',
    'financing.program.benefits.noFees': 'No Hidden Fees',
    'financing.program.benefits.noFees.desc': 'Transparent pricing with no hidden fees or surprise charges throughout the financing process.',
    'financing.program.benefits.quickApproval': 'Quick Approval',
    'financing.program.benefits.quickApproval.desc': 'Fast-track approval process to get you started quickly with minimal paperwork and efficient processing.',
    'financing.program.benefits.flexible': 'Flexible Payment Options',
    'financing.program.benefits.flexible.desc': 'Multiple payment structures available to match your business model and cash flow requirements.',
    'financing.simulator.title': 'Investment Financing Calculator',
    'financing.simulator.description': 'Calculate your financing options and monthly payments with our interactive financing simulator.',
    'financing.signup.ready': 'Ready to Start Your Business Journey?',
    'financing.signup.title': 'Get Started with Our Financing Program',
    'financing.signup.subtitle': 'Take the first step towards your franchise ownership',
    'financing.signup.description': 'Our financing specialists are ready to help you navigate the funding process and find the best solution for your business goals.',
    'financing.signup.description2': 'Schedule a consultation today to discuss your financing needs and learn about our competitive rates and flexible terms.',
    'financing.signup.benefits.consultation': 'Free consultation with financing specialists',
    'financing.signup.benefits.solutions': 'Customized financing solutions for your needs',
    'financing.signup.benefits.guidance': 'Step-by-step guidance through the application process',
    'financing.signup.cta1': 'Schedule Consultation',
    'financing.signup.cta2': 'Apply Now',
    'financing.news.title': 'Financing News & Updates',
    'financing.news.subtitle': 'Stay informed about financing opportunities',
    'financing.news.content': 'Keep up with the latest financing trends, interest rate updates, and new program announcements that could benefit your franchise investment.',

    // Contact
    'contact.hero.badge': 'Contact Us',
    'contact.hero.title': 'Get in Touch with Our Team',
    'contact.hero.subtitle': 'Ready to start your real estate journey? Our experts are here to help you every step of the way.',
    'contact.form.title': 'Send us a Message',
    'contact.form.subtitle': 'Fill out the form below and we will get back to you within 24 hours',
    'contact.form.name': 'Full Name',
    'contact.form.namePlaceholder': 'Enter your full name',
    'contact.form.email': 'Email Address',
    'contact.form.emailPlaceholder': 'Enter your email address',
    'contact.form.phone': 'Phone Number',
    'contact.form.phonePlaceholder': 'Enter your phone number',
    'contact.form.company': 'Company',
    'contact.form.companyPlaceholder': 'Enter your company name',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Tell us about your project or inquiry...',
    'contact.form.send': 'Send Message',
    'contact.info.title': 'Contact Information',
    'contact.info.subtitle': 'Multiple ways to reach our team',
    'contact.info.phone': '+1 (555) 123-4567',
    'contact.info.phoneHours': 'Monday - Friday, 8:00 AM - 6:00 PM EST',
    'contact.info.email': 'info@wmmanagement.com',
    'contact.info.emailResponse': 'We respond within 24 hours',
    'contact.info.address': '123 Business District\nSuite 456\nCity, State 12345',
    'contact.info.hours': 'Business Hours',
    'contact.info.hoursWeekday': 'Monday - Friday: 8:00 AM - 6:00 PM',
    'contact.info.hoursSaturday': 'Saturday: 9:00 AM - 2:00 PM',
    'contact.info.hoursSunday': 'Sunday: Closed',
    'contact.news.title': 'Customer Service Updates',
    'contact.news.subtitle': 'New ways to connect with us',
    'contact.news.content': 'Our live chat feature is now available 24/7 to provide instant support and answer your questions in real-time.',

    // FAQ
    'faq.hero.badge': 'Frequently Asked Questions',
    'faq.hero.title': 'Find Answers to Your Questions',
    'faq.hero.subtitle': 'Get quick answers to the most common questions about our services, financing, and investment opportunities.',
    'faq.services.category': 'Services',
    'faq.services.q1.question': 'What types of real estate services do you offer?',
    'faq.services.q1.answer': 'We offer comprehensive real estate services including property management, investment consulting, commercial leasing, residential sales, and franchise development across multiple industries.',
    'faq.services.q2.question': 'How do you help with property management?',
    'faq.services.q2.answer': 'Our property management services include tenant screening, rent collection, maintenance coordination, financial reporting, and ensuring compliance with local regulations to maximize your property investment returns.',
    'faq.services.q3.question': 'Do you work with both commercial and residential properties?',
    'faq.services.q3.answer': 'Yes, we specialize in both commercial and residential real estate, offering tailored solutions for office buildings, retail spaces, industrial properties, single-family homes, and multi-unit residential complexes.',
    'faq.financing.category': 'Financing',
    'faq.financing.q1.question': 'What financing options are available?',
    'faq.financing.q1.answer': 'We offer various financing solutions including traditional loans, SBA financing, equipment financing, and specialized franchise funding with competitive rates and flexible terms up to 80% of total investment.',
    'faq.financing.q2.question': 'What are the qualification requirements?',
    'faq.financing.q2.answer': 'Qualification requirements include good credit score (typically 650+), sufficient down payment (usually 20-30%), proof of income, business plan for new ventures, and meeting debt-to-income ratio requirements.',
    'faq.financing.q3.question': 'How long does the approval process take?',
    'faq.financing.q3.answer': 'Our streamlined approval process typically takes 2-4 weeks from application submission to final approval, with pre-qualification available within 48-72 hours for qualified applicants.',
    'faq.investments.category': 'Investments',
    'faq.investments.q1.question': 'What investment opportunities do you offer?',
    'faq.investments.q1.answer': 'We offer diverse investment opportunities including direct property ownership, real estate investment trusts (REITs), franchise investments, commercial development projects, and portfolio diversification strategies.',
    'faq.investments.q2.question': 'What is the minimum investment amount?',
    'faq.investments.q2.answer': 'Minimum investment amounts vary by opportunity type, ranging from $25,000 for some REIT investments to $100,000+ for direct property ownership or franchise investments, depending on the specific project.',
    'faq.support.title': 'Need More Help?',
    'faq.support.subtitle': 'Our team is here to assist you',
    'faq.support.contact': 'Contact Support',
    'faq.support.call': 'Call Us Now',
    'faq.news.title': 'FAQ Updates',
    'faq.news.subtitle': 'Recently added questions',
    'faq.news.content': 'We regularly update our FAQ section based on client feedback and new service offerings. Check back frequently for the latest information and answers.',

    // Investment Simulator
    'simulator.title': 'Business Investment Plan Simulator',
    'simulator.description': 'Plan your franchise investment with our interactive tool. Adjust variables to see real-time projections of costs and financing options.',
    'simulator.items.title': 'Investment Items Configuration',
    'simulator.items.description': 'Configure the items and costs for your franchise investment',
    'simulator.items.totalInvestment': 'Total Investment Amount',
    'simulator.tabs.configuration': 'Configuration',
    'simulator.tabs.financing': 'Financing',
    'simulator.tabs.results': 'Results & Analysis',
    'simulator.totalCost.title': 'Total Franchise Cost',
    'simulator.totalCost.description': 'Enter the total investment required for the franchise',
    'simulator.totalCost.label': 'Total Cost ($)',
    'simulator.breakdown.title': 'Cost Breakdown Percentages',
    'simulator.breakdown.description': 'Adjust your total investment allocation',
    'simulator.breakdown.entranceFee': 'Entrance Fee',
    'simulator.breakdown.infrastructure': 'Infrastructure & Renovation',
    'simulator.breakdown.equipment': 'Equipment & Assets',
    'simulator.breakdown.workingCapital': 'Working Capital',
    'simulator.financing.title': 'Financing Details',
    'simulator.financing.description': 'Configure your financing options for infrastructure costs',
    'simulator.financing.percentage': 'Financed Percentage',
    'simulator.financing.term': 'Financing Term (months)',
    'simulator.financing.rate': 'Interest Rate (%)',
    'simulator.property.title': 'Property Details',
    'simulator.property.description': 'Specific details about your franchise location',
    'simulator.property.size': 'Property Size (m²)',
    'simulator.property.costM2': 'Cost per m² ($)',
    'simulator.property.insurance': 'Insurance Cost ($)',
    'simulator.results.costBreakdown': 'Cost Breakdown',
    'simulator.results.costBreakdown.desc': 'Visual representation of your investment allocation',
    'simulator.results.financingBreakdown': 'Financing Breakdown',
    'simulator.results.financingBreakdown.desc': 'Infrastructure financing vs out-of-pocket costs',
    'simulator.results.summary': 'Financial Summary',
    'simulator.results.summary.desc': 'Complete breakdown of your franchise investment',
    'simulator.results.totalInvestment': 'Total Investment',
    'simulator.results.upfrontPayment': 'Upfront Payment',
    'simulator.results.financedAmount': 'Financed Amount',
    'simulator.results.monthlyPayment': 'Monthly Payment',
    'simulator.results.detailedBreakdown': 'Detailed Breakdown:',
    'simulator.results.save': 'Save Scenario',
    'simulator.results.export': 'Export Report',
    'simulator.chart.financed': 'Financed',
    'simulator.chart.outOfPocket': 'Out of Pocket',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Quiénes Somos',
    'nav.services': 'Servicios',
    'nav.industries': 'Industrias y Programas',
    'nav.financing': 'Financiamiento',
    'nav.contact': 'Contacto',
    'nav.faq': 'Preguntas Frecuentes',
    'nav.getStarted': 'Comenzar',
    
    // Home page
    'home.hero.badge': 'Excelencia Inmobiliaria',
    'home.hero.title': 'Bienvenido a WM Management & Investments',
    'home.hero.subtitle': 'En WM, transformamos la complejidad en claridad. Nos apasiona abrazar sus visiones y desafíos, transformando la forma en que vivimos, trabajamos y desarrollamos nuestras comunidades.',
    'home.hero.description': 'Nuestro equipo experimentado y soluciones digitales convierten los complejos desafíos inmobiliarios en oportunidades claras y accionables con éxito medible.',
    'home.hero.cta1': 'Explorar Nuestros Servicios',
    'home.hero.cta2': 'Descubrir Soluciones de Financiamiento',
    'home.hero.feature1': 'Excelencia en Administración de Propiedades',
    'home.hero.feature2': 'Soluciones Estratégicas de Inversión',
    'home.hero.feature3': 'Desarrollo Inmobiliario',
    'home.hero.feature4': 'Servicios Expertos de Consultoría',
    'home.services.title': 'Soluciones Integradas para el Éxito Inmobiliario',
    'home.services.subtitle': 'Desde administración de propiedades hasta servicios de fideicomiso de inversión, entregamos claridad y resultados en todos los aspectos del sector inmobiliario.',
    'home.services.property.title': 'Administración de Propiedades',
    'home.services.property.description': 'Cuidado integral de propiedades desde administración de arrendamientos hasta optimización estratégica.',
    'home.services.brokerage.title': 'Corretaje',
    'home.services.brokerage.description': 'Orientación experta conectando oportunidades con precisión y transparencia.',
    'home.services.consulting.title': 'Servicios de Consultoría',
    'home.services.consulting.description': 'Perspectivas estratégicas que transforman desafíos complejos en oportunidades claras.',
    'home.services.development.title': 'Desarrollo Inmobiliario',
    'home.services.development.description': 'De la visión a la realidad: gestión y ejecución integral de desarrollo.',
    'home.services.investments.title': 'Fideicomiso e Inversiones',
    'home.services.investments.description': 'Marcos de inversión seguros y transparentes con retornos ajustados al riesgo.',
    'home.services.financing.title': 'Soluciones de Financiamiento',
    'home.services.financing.description': 'Financiamiento competitivo con opciones sin intereses para sus proyectos de remodelación.',
    'home.news.title': 'Últimas Noticias y Actualizaciones',
    'home.news.content': 'Manténgase informado sobre las últimas tendencias, oportunidades e insights en el sector inmobiliario. Nuestro equipo comparte regularmente actualizaciones del mercado, consejos de inversión y experiencia de la industria para ayudarle a tomar decisiones informadas.',
    'home.learnMore': 'Saber Más',
    'home.simulator.cta': 'Probar Nuestro Simulador',

    // About page
    'about.hero.badge': 'Nuestra Historia',
    'about.hero.title': 'Transformando la Excelencia Inmobiliaria',
    'about.hero.subtitle': 'Con décadas de experiencia combinada y pasión por la innovación, ayudamos a los clientes a navegar el complejo mundo de los bienes raíces con confianza y claridad.',
    'about.mission.title': 'Nuestra Misión',
    'about.mission.content1': 'En WM Management & Investments, creemos en transformar la complejidad en claridad. Nuestra misión es proporcionar soluciones inmobiliarias integrales que empoderen a nuestros clientes para tomar decisiones informadas y alcanzar sus objetivos de inversión.',
    'about.mission.content2': 'Combinamos conocimiento profundo del mercado con tecnología innovadora para entregar servicios transparentes, eficientes y personalizados en todas nuestras líneas de negocio.',
    'about.vision.title': 'Nuestra Visión',
    'about.vision.content': 'Ser la empresa líder en administración e inversión inmobiliaria, reconocida por nuestra integridad, innovación y compromiso inquebrantable con el éxito del cliente. Visualizamos un futuro donde cada transacción inmobiliaria sea transparente, eficiente y rentable para todas las partes involucradas.',
    'about.news.title': 'Últimas Actualizaciones de la Empresa',
    'about.news.subtitle': 'Manténgase informado sobre nuestro crecimiento',
    'about.news.content': 'Estamos expandiendo continuamente nuestros servicios y capacidades para servir mejor a nuestros clientes. Desde nuevas implementaciones tecnológicas hasta alianzas estratégicas, mantenemos informados a nuestros stakeholders sobre nuestro progreso y planes futuros.',
    'about.team.title': 'Nuestro Equipo',
    'about.team.subtitle': 'Conozca a los profesionales dedicados a su éxito. Nuestro equipo diverso reúne experiencia en bienes raíces, finanzas, tecnología y relaciones con clientes.',
    'about.team.leadership': 'Equipo de Liderazgo',
    'about.team.leadership.desc': 'Ejecutivos experimentados con historiales comprobados en desarrollo inmobiliario, gestión de inversiones y crecimiento empresarial estratégico.',
    'about.team.strategy': 'Planificación Estratégica',
    'about.team.strategy.desc': 'Analistas de mercado y planificadores estratégicos que identifican oportunidades y desarrollan estrategias de inversión integrales para retornos óptimos.',
    'about.team.client': 'Relaciones con Clientes',
    'about.team.client.desc': 'Profesionales dedicados enfocados en entender las necesidades del cliente y brindar servicio personalizado durante cada transacción y asociación.',
    'about.expansion.title': 'Expansión y Crecimiento',
    'about.expansion.subtitle': 'Construyendo para el futuro',
    'about.expansion.content': 'Estamos expandiendo activamente nuestro alcance geográfico y ofertas de servicios para satisfacer las necesidades cambiantes de nuestros clientes. Nuestra estrategia de crecimiento se enfoca en expansión sostenible mientras mantenemos nuestro compromiso con la calidad y el servicio personal.',
    'about.values.title': 'Nuestros Valores Fundamentales',
    'about.values.subtitle': 'Los principios que guían todo lo que hacemos',
    'about.values.transparency': 'Transparencia',
    'about.values.transparency.desc': 'Creemos en la comunicación abierta y honesta y proporcionamos información clara y detallada sobre todos nuestros servicios y procesos.',
    'about.values.integrity': 'Integridad',
    'about.values.integrity.desc': 'Conducimos nuestro negocio con los más altos estándares éticos y siempre actuamos en el mejor interés de nuestros clientes.',
    'about.values.excellence': 'Excelencia',
    'about.values.excellence.desc': 'Nos esforzamos por la calidad excepcional en todos los aspectos de nuestro servicio, mejorando continuamente e innovando para superar las expectativas.',

    // Services page
    'services.hero.badge': 'Nuestros Servicios',
    'services.hero.title': 'Soluciones Inmobiliarias Integrales',
    'services.hero.subtitle': 'Desde administración de propiedades hasta consultoría estratégica, proporcionamos servicios de extremo a extremo diseñados para maximizar sus inversiones inmobiliarias y optimizar sus operaciones.',
    'services.property.title': 'Administración de Propiedades',
    'services.property.description': 'Nuestros servicios integrales de administración de propiedades aseguran que sus inversiones estén bien mantenidas, sean rentables y cumplan con todas las regulaciones mientras proporcionan experiencias excepcionales a los inquilinos.',
    'services.property.features.lease': 'Administración de Arrendamientos',
    'services.property.features.maintenance': 'Coordinación de Mantenimiento',
    'services.property.features.performance': 'Análisis de Rendimiento',
    'services.property.features.reporting': 'Reportes Financieros',
    'services.property.cta': 'Más Sobre Administración de Propiedades',
    'services.brokerage.title': 'Corretaje Inmobiliario',
    'services.brokerage.description': 'Servicios expertos de corretaje que conectan compradores y vendedores con precisión, transparencia y conocimiento profundo del mercado para asegurar transacciones exitosas para todas las partes.',
    'services.brokerage.features.analysis': 'Análisis de Mercado',
    'services.brokerage.features.transaction': 'Gestión de Transacciones',
    'services.brokerage.features.negotiations': 'Negociaciones Expertas',
    'services.brokerage.features.diligence': 'Debida Diligencia',
    'services.brokerage.cta': 'Explorar Servicios de Corretaje',
    'services.consulting.title': 'Consultoría Estratégica',
    'services.consulting.description': 'Perspectivas estratégicas y orientación experta para ayudarle a navegar decisiones inmobiliarias complejas, optimizar portafolios e identificar nuevas oportunidades de inversión.',
    'services.consulting.features.feasibility': 'Estudios de Factibilidad',
    'services.consulting.features.legal': 'Cumplimiento Legal',
    'services.consulting.features.planning': 'Planificación Estratégica',
    'services.consulting.features.research': 'Investigación de Mercado',
    'services.consulting.cta': 'Obtener Consultoría Estratégica',
    'services.development.title': 'Desarrollo Inmobiliario',
    'services.development.description': 'De la visión a la realidad, gestionamos todos los aspectos de los proyectos de desarrollo inmobiliario, asegurando ejecución de calidad, cumplimiento de cronogramas y optimización del presupuesto.',
    'services.development.features.project': 'Gestión de Proyectos',
    'services.development.features.design': 'Coordinación de Diseño',
    'services.development.features.construction': 'Supervisión de Construcción',
    'services.development.features.quality': 'Aseguramiento de Calidad',
    'services.development.cta': 'Iniciar Proyecto de Desarrollo',
    'services.investments.title': 'Servicios de Fideicomiso e Inversión',
    'services.investments.description': 'Marcos de inversión seguros y transparentes diseñados para proporcionar retornos consistentes mientras minimizan el riesgo a través de portafolios inmobiliarios diversificados.',
    'services.investments.features.portfolio': 'Gestión de Portafolio',
    'services.investments.features.risk': 'Evaluación de Riesgo',
    'services.investments.features.strategy': 'Estrategia de Inversión',
    'services.investments.features.monitoring': 'Monitoreo de Rendimiento',
    'services.investments.cta': 'Explorar Opciones de Inversión',
    'services.card.description': 'Servicios profesionales de {service} adaptados a sus necesidades y objetivos específicos.',
    'services.news.title': 'Actualizaciones e Innovaciones de Servicios',
    'services.news.subtitle': 'Manteniéndonos a la vanguardia con nuevas capacidades',
    'services.news.content': 'Mejoramos continuamente nuestras ofertas de servicios con nuevas tecnologías, capacidades expandidas y soluciones innovadoras para servir mejor las necesidades cambiantes de nuestros clientes.',
    'services.cta.description': '¿Listo para transformar su experiencia inmobiliaria? Contáctenos hoy para discutir cómo nuestros servicios integrales pueden ayudarle a alcanzar sus objetivos.',

    // Industries page
    'industries.hero.badge': 'Industrias y Programas',
    'industries.hero.title': 'Soluciones Especializadas por Industria',
    'industries.hero.subtitle': 'Proporcionamos soluciones inmobiliarias personalizadas para diversas industrias, entendiendo los requisitos únicos y desafíos de cada sector para entregar resultados óptimos.',
    'industries.overview.title': 'Experiencia Industrial en Todos los Sectores',
    'industries.overview.subtitle': 'Comprensión integral de las necesidades y regulaciones específicas de la industria',
    'industries.overview.description': 'Nuestro conocimiento profundo de la industria nos permite proporcionar servicios especializados que abordan los desafíos únicos y oportunidades dentro de cada sector. Desde requisitos de cumplimiento hasta necesidades operacionales, entregamos soluciones que impulsan el éxito.',
    'industries.sectors.title': 'Sectores Industriales que Servimos',
    'industries.sectors.subtitle': 'Experiencia especializada en múltiples industrias',
    'industries.residential.title': 'Bienes Raíces Residenciales',
    'industries.residential.description': 'Soluciones integrales de propiedades residenciales incluyendo casas unifamiliares, condominios y desarrollos multifamiliares con enfoque en construcción de comunidad y satisfacción del residente.',
    'industries.residential.cta': 'Explorar Servicios Residenciales',
    'industries.commercial.title': 'Propiedades Comerciales',
    'industries.commercial.description': 'Servicios estratégicos de bienes raíces comerciales para edificios de oficinas, espacios de venta al por menor y desarrollos de uso mixto que maximizan el valor y la eficiencia operacional.',
    'industries.commercial.cta': 'Conocer Soluciones Comerciales',
    'industries.health.title': 'Instalaciones de Salud',
    'industries.health.description': 'Servicios especializados de bienes raíces para el cuidado de la salud asegurando cumplimiento con regulaciones de instalaciones médicas mientras optimizan ambientes de atención al paciente y flujos de trabajo operacionales.',
    'industries.health.cta': 'Soluciones Inmobiliarias para Salud',
    'industries.industrial.title': 'Propiedades Industriales',
    'industries.industrial.description': 'Gestión experta de instalaciones industriales, plantas de manufactura y centros de distribución con enfoque en eficiencia operacional y cumplimiento de seguridad.',
    'industries.industrial.cta': 'Servicios de Propiedades Industriales',
    'industries.logistics.title': 'Logística y Almacenamiento',
    'industries.logistics.description': 'Soluciones especializadas de bienes raíces logísticos para almacenes, centros de distribución e instalaciones de cadena de suministro optimizadas para las demandas del comercio moderno.',
    'industries.logistics.cta': 'Servicios Inmobiliarios Logísticos',
    'industries.governments.title': 'Gobierno y Sector Público',
    'industries.governments.description': 'Servicios de bienes raíces del sector público con comprensión profunda de regulaciones gubernamentales, procesos de adquisición y requisitos de desarrollo comunitario.',
    'industries.governments.cta': 'Servicios Gubernamentales',
    'industries.stats.title': 'Nuestro Impacto Industrial',
    'industries.stats.subtitle': 'Entregando resultados en todos los sectores',
    'industries.stats.projects': 'Proyectos Completados',
    'industries.stats.clients': 'Clientes de la Industria',
    'industries.stats.years': 'Años de Experiencia',
    'industries.news.title': 'Perspectivas y Actualizaciones de la Industria',
    'industries.news.subtitle': 'Manteniéndonos adelante de las tendencias industriales',
    'industries.news.content': 'Monitoreamos continuamente las tendencias de la industria, cambios regulatorios y desarrollos del mercado para asegurar que nuestros clientes se mantengan adelante de la curva y capitalicen en oportunidades emergentes.',

    // Common
    'common.readyToStart': '¿Listo para Comenzar?',
    'common.contactTeam': 'Contactar Nuestro Equipo',
    'common.keyFeatures': 'Características Clave:',
    'common.language': 'Idioma',
    'common.trySimulator': 'Probar Nuestro Simulador',
    'common.submit': 'Enviar',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.required': 'Requerido',
    'common.optional': 'Opcional',
    'common.learnMore': 'Saber Más',
    'common.contactUs': 'Contáctenos',
    'common.phone': 'Teléfono',
    'common.email': 'Correo Electrónico',
    'common.address': 'Dirección',
    'common.name': 'Nombre',
    'common.message': 'Mensaje',
    'common.send': 'Enviar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.close': 'Cerrar',
    'common.open': 'Abrir',

    // Financing
    'financing.hero.badge': 'Financiamiento de Franquicia',
    'financing.hero.title': 'Soluciones de Financiamiento Flexibles para Su Negocio',
    'financing.hero.subtitle': 'Acceda al capital que necesita para iniciar su franquicia con nuestros programas de financiamiento integral diseñados para el éxito.',
    'financing.program.title': 'Nuestro Programa de Financiamiento',
    'financing.program.description1': 'Entendemos que iniciar una franquicia requiere una inversión de capital significativa. Nuestras soluciones de financiamiento especializadas están diseñadas para ayudar a los emprendedores a acceder al financiamiento que necesitan para lanzar y hacer crecer su negocio.',
    'financing.program.description2': 'Con tasas competitivas, términos flexibles y procesos de aprobación rápidos, facilitamos que los candidatos calificados aseguren el financiamiento necesario para su inversión de franquicia.',
    'financing.program.features.interest': 'Tasas de Interés Competitivas',
    'financing.program.features.interest.desc': 'Benefíciese de tasas de interés competitivas que hacen su financiamiento asequible y manejable.',
    'financing.program.features.terms': 'Términos Flexibles',
    'financing.program.features.terms.desc': 'Elija entre varias opciones de plazo que se alineen con el flujo de efectivo y las proyecciones de crecimiento de su negocio.',
    'financing.program.features.secure': 'Proceso Seguro',
    'financing.program.features.secure.desc': 'Nuestro proceso seguro de solicitud y aprobación protege su información mientras acelera su financiamiento.',
    'financing.program.features.coverage': 'Cobertura Integral',
    'financing.program.features.coverage.desc': 'Financie hasta el 80% de su inversión total de franquicia, incluyendo equipos, renovación y capital de trabajo.',
    'financing.program.cta': 'Solicitar Financiamiento',
    'financing.program.benefits.title': 'Beneficios del Programa',
    'financing.program.benefits.subtitle': 'Por qué elegir nuestra solución de financiamiento',
    'financing.program.benefits.noFees': 'Sin Tarifas Ocultas',
    'financing.program.benefits.noFees.desc': 'Precios transparentes sin tarifas ocultas o cargos sorpresa durante el proceso de financiamiento.',
    'financing.program.benefits.quickApproval': 'Aprobación Rápida',
    'financing.program.benefits.quickApproval.desc': 'Proceso de aprobación acelerado para comenzar rápidamente con papeleo mínimo y procesamiento eficiente.',
    'financing.program.benefits.flexible': 'Opciones de Pago Flexibles',
    'financing.program.benefits.flexible.desc': 'Múltiples estructuras de pago disponibles para coincidir con su modelo de negocio y requisitos de flujo de efectivo.',
    'financing.simulator.title': 'Calculadora de Financiamiento de Inversión',
    'financing.simulator.description': 'Calcule sus opciones de financiamiento y pagos mensuales con nuestro simulador de financiamiento interactivo.',
    'financing.signup.ready': '¿Listo para Comenzar Su Jornada Empresarial?',
    'financing.signup.title': 'Comience con Nuestro Programa de Financiamiento',
    'financing.signup.subtitle': 'Dé el primer paso hacia la propiedad de su franquicia',
    'financing.signup.description': 'Nuestros especialistas en financiamiento están listos para ayudarle a navegar el proceso de financiamiento y encontrar la mejor solución para sus objetivos empresariales.',
    'financing.signup.description2': 'Programe una consulta hoy para discutir sus necesidades de financiamiento y conocer nuestras tasas competitivas y términos flexibles.',
    'financing.signup.benefits.consultation': 'Consulta gratuita con especialistas en financiamiento',
    'financing.signup.benefits.solutions': 'Soluciones de financiamiento personalizadas para sus necesidades',
    'financing.signup.benefits.guidance': 'Orientación paso a paso a través del proceso de solicitud',
    'financing.signup.cta1': 'Programar Consulta',
    'financing.signup.cta2': 'Aplicar Ahora',
    'financing.news.title': 'Noticias y Actualizaciones de Financiamiento',
    'financing.news.subtitle': 'Manténgase informado sobre oportunidades de financiamiento',
    'financing.news.content': 'Manténgase al día con las últimas tendencias de financiamiento, actualizaciones de tasas de interés y anuncios de nuevos programas que podrían beneficiar su inversión de franquicia.',

    // Contact
    'contact.hero.badge': 'Contáctanos',
    'contact.hero.title': 'Ponte en Contacto con Nuestro Equipo',
    'contact.hero.subtitle': '¿Listo para comenzar su jornada inmobiliaria? Nuestros expertos están aquí para ayudarle en cada paso del camino.',
    'contact.form.title': 'Envíanos un Mensaje',
    'contact.form.subtitle': 'Complete el formulario a continuación y le responderemos dentro de 24 horas',
    'contact.form.name': 'Nombre Completo',
    'contact.form.namePlaceholder': 'Ingrese su nombre completo',
    'contact.form.email': 'Dirección de Correo',
    'contact.form.emailPlaceholder': 'Ingrese su dirección de correo',
    'contact.form.phone': 'Número de Teléfono',
    'contact.form.phonePlaceholder': 'Ingrese su número de teléfono',
    'contact.form.company': 'Empresa',
    'contact.form.companyPlaceholder': 'Ingrese el nombre de su empresa',
    'contact.form.message': 'Mensaje',
    'contact.form.messagePlaceholder': 'Cuéntenos sobre su proyecto o consulta...',
    'contact.form.send': 'Enviar Mensaje',
    'contact.info.title': 'Información de Contacto',
    'contact.info.subtitle': 'Múltiples formas de contactar a nuestro equipo',
    'contact.info.phone': '+1 (555) 123-4567',
    'contact.info.phoneHours': 'Lunes - Viernes, 8:00 AM - 6:00 PM EST',
    'contact.info.email': 'info@wmmanagement.com',
    'contact.info.emailResponse': 'Respondemos dentro de 24 horas',
    'contact.info.address': '123 Distrito de Negocios\nSuite 456\nCiudad, Estado 12345',
    'contact.info.hours': 'Horarios de Atención',
    'contact.info.hoursWeekday': 'Lunes - Viernes: 8:00 AM - 6:00 PM',
    'contact.info.hoursSaturday': 'Sábado: 9:00 AM - 2:00 PM',
    'contact.info.hoursSunday': 'Domingo: Cerrado',
    'contact.news.title': 'Actualizaciones de Servicio al Cliente',
    'contact.news.subtitle': 'Nuevas formas de conectarse con nosotros',
    'contact.news.content': 'Nuestra función de chat en vivo ahora está disponible 24/7 para brindar soporte instantáneo y responder sus preguntas en tiempo real.',

    // FAQ
    'faq.hero.badge': 'Preguntas Frecuentes',
    'faq.hero.title': 'Encuentra Respuestas a Tus Preguntas',
    'faq.hero.subtitle': 'Obtén respuestas rápidas a las preguntas más comunes sobre nuestros servicios, financiamiento y oportunidades de inversión.',
    'faq.services.category': 'Servicios',
    'faq.services.q1.question': '¿Qué tipos de servicios inmobiliarios ofrecen?',
    'faq.services.q1.answer': 'Ofrecemos servicios inmobiliarios integrales incluyendo administración de propiedades, consultoría de inversiones, arrendamiento comercial, ventas residenciales y desarrollo de franquicias en múltiples industrias.',
    'faq.services.q2.question': '¿Cómo ayudan con la administración de propiedades?',
    'faq.services.q2.answer': 'Nuestros servicios de administración de propiedades incluyen selección de inquilinos, cobro de rentas, coordinación de mantenimiento, reportes financieros y garantizar cumplimiento con regulaciones locales para maximizar el retorno de su inversión inmobiliaria.',
    'faq.services.q3.question': '¿Trabajan tanto con propiedades comerciales como residenciales?',
    'faq.services.q3.answer': 'Sí, nos especializamos tanto en bienes raíces comerciales como residenciales, ofreciendo soluciones personalizadas para edificios de oficinas, espacios comerciales, propiedades industriales, casas unifamiliares y complejos residenciales multifamiliares.',
    'faq.financing.category': 'Financiamiento',
    'faq.financing.q1.question': '¿Qué opciones de financiamiento están disponibles?',
    'faq.financing.q1.answer': 'Ofrecemos varias soluciones de financiamiento incluyendo préstamos tradicionales, financiamiento SBA, financiamiento de equipos y fondos especializados para franquicias con tasas competitivas y términos flexibles hasta el 80% de la inversión total.',
    'faq.financing.q2.question': '¿Cuáles son los requisitos de calificación?',
    'faq.financing.q2.answer': 'Los requisitos de calificación incluyen buen puntaje crediticio (típicamente 650+), enganche suficiente (usualmente 20-30%), comprobante de ingresos, plan de negocios para nuevas empresas y cumplir con los requisitos de relación deuda-ingreso.',
    'faq.financing.q3.question': '¿Cuánto tiempo toma el proceso de aprobación?',
    'faq.financing.q3.answer': 'Nuestro proceso de aprobación simplificado típicamente toma 2-4 semanas desde la presentación de la solicitud hasta la aprobación final, con precalificación disponible dentro de 48-72 horas para solicitantes calificados.',
    'faq.investments.category': 'Inversiones',
    'faq.investments.q1.question': '¿Qué oportunidades de inversión ofrecen?',
    'faq.investments.q1.answer': 'Ofrecemos diversas oportunidades de inversión incluyendo propiedad directa de bienes raíces, fondos de inversión inmobiliaria (REITs), inversiones en franquicias, proyectos de desarrollo comercial y estrategias de diversificación de portafolio.',
    'faq.investments.q2.question': '¿Cuál es el monto mínimo de inversión?',
    'faq.investments.q2.answer': 'Los montos mínimos de inversión varían según el tipo de oportunidad, desde $25,000 para algunas inversiones REIT hasta $100,000+ para propiedad directa o inversiones en franquicias, dependiendo del proyecto específico.',
    'faq.support.title': '¿Necesitas Más Ayuda?',
    'faq.support.subtitle': 'Nuestro equipo está aquí para asistirte',
    'faq.support.contact': 'Contactar Soporte',
    'faq.support.call': 'Llámanos Ahora',
    'faq.news.title': 'Actualizaciones de FAQ',
    'faq.news.subtitle': 'Preguntas agregadas recientemente',
    'faq.news.content': 'Actualizamos regularmente nuestra sección de FAQ basándose en comentarios de clientes y nuevas ofertas de servicios. Consulte frecuentemente para obtener la información más reciente y respuestas.',

    // Investment Simulator
    'simulator.title': 'Simulador de Plan de Inversión de Negocio',
    'simulator.description': 'Planifique su inversión de franquicia con nuestra herramienta interactiva. Ajuste variables para ver proyecciones en tiempo real de costos y opciones de financiamiento.',
    'simulator.items.title': 'Configuración de Artículos de Inversión',
    'simulator.items.description': 'Configure los artículos y costos para su inversión de franquicia',
    'simulator.items.totalInvestment': 'Monto Total de Inversión',
    'simulator.tabs.configuration': 'Configuración',
    'simulator.tabs.financing': 'Financiamiento',
    'simulator.tabs.results': 'Resultados y Análisis',
    'simulator.totalCost.title': 'Costo Total de Franquicia',
    'simulator.totalCost.description': 'Ingrese la inversión total requerida para la franquicia',
    'simulator.totalCost.label': 'Costo Total ($)',
    'simulator.breakdown.title': 'Porcentajes de Desglose de Costos',
    'simulator.breakdown.description': 'Ajuste la asignación de su inversión total',
    'simulator.breakdown.entranceFee': 'Cuota de Entrada',
    'simulator.breakdown.infrastructure': 'Infraestructura y Remodelación',
    'simulator.breakdown.equipment': 'Equipos y Activos',
    'simulator.breakdown.workingCapital': 'Capital de Trabajo',
    'simulator.financing.title': 'Detalles de Financiamiento',
    'simulator.financing.description': 'Configure sus opciones de financiamiento para costos de infraestructura',
    'simulator.financing.percentage': 'Porcentaje Financiado',
    'simulator.financing.term': 'Plazo de Financiamiento (meses)',
    'simulator.financing.rate': 'Tasa de Interés (%)',
    'simulator.property.title': 'Detalles de la Propiedad',
    'simulator.property.description': 'Detalles específicos sobre la ubicación de su franquicia',
    'simulator.property.size': 'Tamaño del Local (m²)',
    'simulator.property.costM2': 'Costo por m² ($)',
    'simulator.property.insurance': 'Costo de Seguro ($)',
    'simulator.results.costBreakdown': 'Desglose de Costos',
    'simulator.results.costBreakdown.desc': 'Representación visual de la asignación de su inversión',
    'simulator.results.financingBreakdown': 'Desglose de Financiamiento',
    'simulator.results.financingBreakdown.desc': 'Financiamiento de infraestructura vs costos de bolsillo',
    'simulator.results.summary': 'Resumen Financiero',
    'simulator.results.summary.desc': 'Desglose completo de su inversión de franquicia',
    'simulator.results.totalInvestment': 'Inversión Total',
    'simulator.results.upfrontPayment': 'Pago Inicial',
    'simulator.results.financedAmount': 'Monto Financiado',
    'simulator.results.monthlyPayment': 'Pago Mensual',
    'simulator.results.detailedBreakdown': 'Desglose Detallado:',
    'simulator.results.save': 'Guardar Escenario',
    'simulator.results.export': 'Exportar Reporte',
    'simulator.chart.financed': 'Financiado',
    'simulator.chart.outOfPocket': 'De su Bolsillo',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
