import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.industries': 'Industries & Programs',
    'nav.financing': 'Financing',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.getStarted': 'Get Started',
    
    // Home page
    'home.hero.badge': 'Real Estate Excellence',
    'home.hero.title': 'Welcome to WM Management & Investments',
    'home.hero.subtitle': 'At WM, we transform complexity into clarity. We are passionate about embracing your visions and challenges, transforming the way we live, work, and develop our communities.',
    'home.hero.description': 'Our experienced team and digital solutions turn intricate real estate challenges into straightforward, actionable opportunities with measurable success.',
    'home.hero.cta1': 'Explore Our Services',
    'home.hero.cta2': 'Discover Financing Solutions',
    'home.hero.feature1': 'Property Management Excellence',
    'home.hero.feature2': 'Strategic Investment Solutions',
    'home.hero.feature3': 'Real Estate Development',
    'home.hero.feature4': 'Expert Consulting Services',
    'home.services.title': 'Integrated Solutions for Real Estate Success',
    'home.services.subtitle': 'From property management to investment trust services, we deliver clarity and results across every aspect of real estate.',
    'home.services.property.title': 'Property Management',
    'home.services.property.description': 'Comprehensive property care from lease administration to strategic optimization.',
    'home.services.brokerage.title': 'Brokerage',
    'home.services.brokerage.description': 'Expert guidance connecting opportunities with precision and transparency.',
    'home.services.consulting.title': 'Consulting Services',
    'home.services.consulting.description': 'Strategic insights that transform complex challenges into clear opportunities.',
    'home.services.development.title': 'Real Estate Development',
    'home.services.development.description': 'From vision to reality—comprehensive development management and execution.',
    'home.services.investments.title': 'Trust & Investments',
    'home.services.investments.description': 'Secure, transparent investment frameworks with risk-adjusted returns.',
    'home.services.financing.title': 'Financing Solutions',
    'home.services.financing.description': 'Competitive financing with interest-free options for your remodeling projects.',
    'home.simulator.cta': 'Try Our Simulator',
    'home.learnMore': 'Learn More',
    'home.news.title': 'News & Updates – March 2025',
    'home.news.content': 'New Market Insights: Our latest research highlights emerging trends in property management that are revolutionizing the industry. Check back monthly for fresh updates and actionable strategies.',
    
    // About page
    'about.hero.badge': 'About WM Management',
    'about.hero.title': 'Transforming Real Estate Challenges into Opportunities',
    'about.hero.subtitle': 'We leverage data-driven insights and deep industry expertise to deliver solutions that add real value to every client relationship.',
    'about.mission.title': 'Our Mission',
    'about.mission.content1': 'At WM Management & Investments, our mission is to convert real estate challenges into tangible opportunities. We leverage data-driven insights and deep industry expertise to deliver solutions that add real value.',
    'about.mission.content2': 'We believe that by embracing transparency, integrity, and a pragmatic approach, we can empower every investor to reach their full potential.',
    'about.vision.title': 'Our Vision',
    'about.vision.content': 'Our vision is to be the trusted partner that simplifies the complex world of real estate, enabling our clients to make informed decisions and achieve lasting success.',
    'about.team.title': 'Meet Our Team',
    'about.team.subtitle': 'Our team is our cornerstone. Composed of industry veterans and innovative strategists, we bring together a wealth of experience and fresh ideas to drive success.',
    'about.team.leadership': 'Leadership Team',
    'about.team.leadership.desc': 'Industry veterans with decades of combined experience in real estate management and investment.',
    'about.team.strategy': 'Strategy Experts',
    'about.team.strategy.desc': 'Data analysts and strategic planners who transform market insights into actionable opportunities.',
    'about.team.client': 'Client Partners',
    'about.team.client.desc': 'Dedicated professionals who work side by side with clients to craft effective, innovative solutions.',
    'about.values.title': 'Our Core Values',
    'about.values.subtitle': 'The principles that guide every decision and drive our success',
    'about.values.transparency': 'Transparency',
    'about.values.transparency.desc': 'Clear communication and honest reporting in every interaction and transaction.',
    'about.values.integrity': 'Integrity',
    'about.values.integrity.desc': 'Ethical practices and principled decision-making that builds lasting trust.',
    'about.values.excellence': 'Excellence',
    'about.values.excellence.desc': 'Committed to delivering exceptional results through continuous improvement and innovation.',
    
    // Services page
    'services.hero.badge': 'Professional Services',
    'services.hero.title': 'Comprehensive Real Estate Solutions',
    'services.hero.subtitle': 'Our services are at the heart of what we do. Each offering is designed to deliver clarity, drive value, and provide measurable results.',
    'services.property.title': 'Property Management',
    'services.property.description': 'Managing your property shouldn\'t be complicated. Our property management service covers everything from lease administration and routine maintenance to strategic performance optimization.',
    'services.brokerage.title': 'Brokerage',
    'services.brokerage.description': 'Real estate transactions demand precision and transparency. Our brokerage services connect buyers, sellers, and lessees with the best opportunities available.',
    'services.consulting.title': 'Consulting Services',
    'services.consulting.description': 'When complexity meets clarity, success follows. Our consulting services break down real estate challenges into clear, actionable strategies.',
    'services.development.title': 'Real Estate Development',
    'services.development.description': 'Turning vision into reality—our real estate development team manages projects from concept through completion with innovative design and strategic planning.',
    'services.investments.title': 'Trust & Investments',
    'services.investments.description': 'Invest with assurance. Our trust and investment services provide a secure and transparent framework for managing real estate assets.',
    'services.property.features.lease': 'Lease Administration',
    'services.property.features.maintenance': 'Maintenance Management',
    'services.property.features.performance': 'Performance Optimization',
    'services.property.features.reporting': 'Financial Reporting',
    'services.property.cta': 'Learn How We Maximize Property Value',
    'services.brokerage.features.analysis': 'Market Analysis',
    'services.brokerage.features.transaction': 'Transaction Management',
    'services.brokerage.features.negotiations': 'Expert Negotiations',
    'services.brokerage.features.diligence': 'Due Diligence Support',
    'services.brokerage.cta': 'Explore Current Opportunities',
    'services.consulting.features.feasibility': 'Feasibility Studies',
    'services.consulting.features.legal': 'Legal Advisory',
    'services.consulting.features.planning': 'Strategic Planning',
    'services.consulting.features.research': 'Market Research',
    'services.consulting.cta': 'Request Your Consultation',
    'services.development.features.project': 'Project Management',
    'services.development.features.design': 'Design Integration',
    'services.development.features.construction': 'Construction Oversight',
    'services.development.features.quality': 'Quality Assurance',
    'services.development.cta': 'Discover Our Development Projects',
    'services.investments.features.portfolio': 'Portfolio Management',
    'services.investments.features.risk': 'Risk Assessment',
    'services.investments.features.strategy': 'Investment Strategy',
    'services.investments.features.monitoring': 'Performance Monitoring',
    'services.investments.cta': 'Find Out More About Our Investment Solutions',
    'services.card.description': 'Professional {service} services tailored to your specific needs and objectives.',
    'services.news.title': 'News & Updates – March 2025',
    'services.news.subtitle': 'Latest developments in our services',
    'services.cta.description': 'Let us help you transform your real estate challenges into strategic opportunities.',
    
    // Common
    'common.readyToStart': 'Ready to Get Started?',
    'common.contactTeam': 'Contact Our Team',
    'common.keyFeatures': 'Key Features:',
    'common.language': 'Language',
    'common.trySimulator': 'Try Our Simulator',
    
    // Footer
    'footer.description': 'Transforming complexity into clarity. Your trusted partner in real estate consulting, investment, and development.',
    
    // Industries & Programs page
    'industries.hero.badge': 'Industries & Programs',
    'industries.hero.title': 'Property Management Across Industries',
    'industries.hero.subtitle': 'From residential foundations to specialized commercial sectors, we deliver comprehensive property management solutions tailored to each industry\'s unique requirements.',
    'industries.overview.title': 'From Residential to Specialized Sectors',
    'industries.overview.subtitle': 'Our management expertise spans from residential properties to complex commercial and institutional facilities',
    'industries.overview.description': 'Starting with a solid foundation in residential property management, we have expanded our expertise to serve diverse industries. Our comprehensive approach ensures that whether you own a single-family home or a complex industrial facility, we provide the same level of professional management and strategic optimization.',
    'industries.sectors.title': 'Specialized Industry Management',
    'industries.sectors.subtitle': 'Targeted solutions for specific industry requirements and challenges',
    'industries.residential.title': 'Residential Properties',
    'industries.residential.description': 'Comprehensive management of single-family homes, condominiums, and multi-family residential properties. We focus on tenant satisfaction, property maintenance, and maximizing rental returns while preserving property value.',
    'industries.residential.cta': 'Explore Residential Management',
    'industries.commercial.title': 'Commercial Properties',
    'industries.commercial.description': 'Professional management of office buildings, retail spaces, and mixed-use developments. We optimize tenant satisfaction, maximize occupancy rates, and ensure properties operate efficiently while maintaining strong investor returns.',
    'industries.commercial.cta': 'Explore Commercial Management',
    'industries.health.title': 'Healthcare Facilities',
    'industries.health.description': 'Specialized management for medical facilities, clinics, and healthcare complexes. We understand the critical importance of compliance, patient safety, and operational efficiency in healthcare environments.',
    'industries.health.cta': 'Discover Healthcare Solutions',
    'industries.industrial.title': 'Industrial & Manufacturing',
    'industries.industrial.description': 'Management of warehouses, manufacturing facilities, and distribution centers. We focus on operational efficiency, safety compliance, and maintaining the specialized infrastructure these properties require.',
    'industries.industrial.cta': 'Learn About Industrial Management',
    'industries.logistics.title': 'Logistics & Distribution',
    'industries.logistics.description': 'Strategic management of logistics hubs and distribution centers. Our approach optimizes traffic flow, loading efficiency, and tenant operations while maintaining the high standards required for supply chain success.',
    'industries.logistics.cta': 'Optimize Your Logistics Property',
    'industries.governments.title': 'Government & Institutional',
    'industries.governments.description': 'Management of government buildings, educational institutions, and public facilities. We provide reliable, cost-effective management while ensuring compliance with public sector requirements and maintaining community standards.',
    'industries.governments.cta': 'View Public Sector Management',
    'industries.stats.title': 'Our Track Record',
    'industries.stats.subtitle': 'Proven results across multiple industries',
    'industries.stats.projects': 'Completed Projects',
    'industries.stats.clients': 'Industry Partners',
    'industries.stats.years': 'Years of Experience',
    'industries.news.title': 'News & Updates – March 2025',
    'industries.news.subtitle': 'Latest industry insights',
    'industries.news.content': 'Urban Trends Report: Our latest insights from top urban economics research reveal innovative strategies for modern city planning. Stay updated for more groundbreaking findings every month.',
    
    // FAQ page
    'faq.hero.badge': 'FAQ',
    'faq.hero.title': 'Frequently Asked Questions',
    'faq.hero.subtitle': 'We understand that clarity is key. Here, you will find straightforward answers to our most common questions about our services, financing, and processes.',
    'faq.services.category': 'Services',
    'faq.services.q1.question': 'What services does WM Management & Investments offer?',
    'faq.services.q1.answer': 'We offer comprehensive real estate solutions including property management, brokerage services, consulting, real estate development, and trust & investment services.',
    'faq.services.q2.question': 'How do you ensure quality in property management?',
    'faq.services.q2.answer': 'Our property management service covers everything from lease administration and routine maintenance to strategic performance optimization, ensuring every property operates at peak efficiency.',
    'faq.services.q3.question': 'What makes your consulting services different?',
    'faq.services.q3.answer': 'Our consulting services break down complex real estate challenges into clear, actionable strategies, leveraging data-driven insights and deep industry expertise.',
    'faq.financing.category': 'Financing',
    'faq.financing.q1.question': 'What financing options do you offer?',
    'faq.financing.q1.answer': 'We offer competitive financing with interest-free options for up to 50% of your remodeling costs, with flexible terms up to 60 months.',
    'faq.financing.q2.question': 'How does the financing approval process work?',
    'faq.financing.q2.answer': 'Our streamlined approval process is designed for quick decision making. We provide fast approval with transparent pricing and no hidden fees.',
    'faq.financing.q3.question': 'Can I use the simulator before applying?',
    'faq.financing.q3.answer': 'Yes! Our interactive simulator lets you experiment with different financing scenarios in real-time to help you plan confidently.',
    'faq.investments.category': 'Investments',
    'faq.investments.q1.question': 'What types of investment opportunities do you provide?',
    'faq.investments.q1.answer': 'Our trust and investment services provide a secure and transparent framework for managing real estate assets, delivering sustainable, risk-adjusted returns.',
    'faq.investments.q2.question': 'How do you ensure investment security?',
    'faq.investments.q2.answer': 'We combine financial expertise with deep market insights and maintain strict transparency standards to ensure secure investment frameworks.',
    'faq.support.title': 'Still Have Questions?',
    'faq.support.subtitle': 'Our team is just a click away to provide personalized assistance.',
    'faq.support.contact': 'Contact Us',
    'faq.support.call': 'Call Us',
    'faq.news.title': 'News & Updates – March 2025',
    'faq.news.subtitle': 'Latest FAQ updates',
    'faq.news.content': 'New FAQ Items: Based on customer feedback, we have added answers to the latest questions regarding our consulting and financing processes.',
    
    // Financing page translations
    'financing.hero.badge': 'Financing Solutions',
    'financing.hero.title': 'Smart Financing for Your Success',
    'financing.hero.subtitle': 'Our financing solutions are crafted to break down barriers and accelerate growth, offering clear and accessible options for every project.',
    'financing.program.title': 'The Program',
    'financing.program.description1': 'Our financing program is designed with simplicity and efficiency in mind. With competitive setup fees and interest-free financing for 50% of your remodeling costs, we remove obstacles and empower you to move forward with confidence.',
    'financing.program.description2': 'We believe in creating clear pathways to success by eliminating unnecessary financial complexity.',
    'financing.program.cta': 'Discover the Program',
    'financing.simulator.title': 'Interactive Simulator',
    'financing.simulator.description': 'Transparency is key to smart financing. Our interactive simulator lets you experiment with different financing scenarios in real-time.',
    'financing.simulator.cta': 'Try the Simulator Now',
    'financing.signup.title': 'Sign Up Today',
    'financing.signup.description': 'Join our financing program and take the first step toward achieving your real estate goals with confidence and clarity.',
    'financing.signup.ready': 'Ready to Get Started?',
    'financing.signup.subtitle': 'Whether you\'re an investor, franchisee, or property owner, sign up for our financing program',
    'financing.signup.description2': 'Ready to turn potential into performance? Sign up for our financing program and receive personalized guidance from our experts. We\'re committed to making your vision a reality through clear, supportive steps.',
    'financing.signup.cta1': 'Sign Up for Financing Program',
    'financing.signup.cta2': 'Try the Simulator First',
    'financing.news.title': 'News & Updates – March 2025',
    'financing.news.subtitle': 'Latest enhancements to our financing solutions',
    'financing.news.content': 'Enhanced Simulator: Our tool now includes the latest economic data to provide even more precise investment projections. Explore the new features and see the difference today!',
    
    // Contact page translations
    'contact.hero.badge': 'Contact Us',
    'contact.hero.title': 'Get in Touch',
    'contact.hero.subtitle': 'We are here to help you transform your ideas into actionable success. Whether you have questions about our services, financing options, or need personalized advice, please reach out.',
    'contact.form.title': 'Send us a Message',
    'contact.form.subtitle': 'Fill out the form and our team will get back to you within 48 hours',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.company': 'Company (Optional)',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.info.title': 'Contact Information',
    'contact.info.subtitle': 'Our team is ready to provide clear, prompt assistance. Your success is our priority.',
    'contact.news.title': 'News & Updates – March 2025',
    'contact.news.subtitle': 'Enhanced support options',
    'contact.news.content': 'Live Chat Now Available: We\'ve extended our live support hours to ensure you receive immediate assistance whenever you need it.',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Quiénes Somos',
    'nav.services': 'Servicios',
    'nav.industries': 'Industrias y Programas',
    'nav.financing': 'Financiamiento',
    'nav.contact': 'Contacto',
    'nav.faq': 'Preguntas Frecuentes',
    'nav.getStarted': 'Comenzar',
    
    // Home page
    'home.hero.badge': 'Excelencia Inmobiliaria',
    'home.hero.title': 'Bienvenido a WM Management & Investments',
    'home.hero.subtitle': 'En WM, transformamos la complejidad en claridad. Somos apasionados por abrazar sus visiones y desafíos, transformando la forma en que vivimos, trabajamos y desarrollamos nuestras comunidades.',
    'home.hero.description': 'Nuestro equipo experimentado y las soluciones digitales convierten los complejos desafíos inmobiliarios en oportunidades claras y accionables con éxito medible.',
    'home.hero.cta1': 'Explorar Nuestros Servicios',
    'home.hero.cta2': 'Descubrir Soluciones de Financiamiento',
    'home.hero.feature1': 'Excelencia en Gestión de Propiedades',
    'home.hero.feature2': 'Soluciones Estratégicas de Inversión',
    'home.hero.feature3': 'Desarrollo Inmobiliario',
    'home.hero.feature4': 'Servicios Expertos de Consultoría',
    'home.services.title': 'Soluciones Integradas para el Éxito Inmobiliario',
    'home.services.subtitle': 'Desde la gestión de propiedades hasta los servicios de fideicomiso de inversión, ofrecemos claridad y resultados en cada aspecto de los bienes raíces.',
    'home.services.property.title': 'Gestión de Propiedades',
    'home.services.property.description': 'Cuidado integral de propiedades desde la administración de arrendamientos hasta la optimización estratégica.',
    'home.services.brokerage.title': 'Corretaje',
    'home.services.brokerage.description': 'Orientación experta conectando oportunidades con precisión y transparencia.',
    'home.services.consulting.title': 'Servicios de Consultoría',
    'home.services.consulting.description': 'Insights estratégicos que transforman desafíos complejos en oportunidades claras.',
    'home.services.development.title': 'Desarrollo Inmobiliario',
    'home.services.development.description': 'De la visión a la realidad—gestión y ejecución integral de desarrollo.',
    'home.services.investments.title': 'Fideicomisos e Inversiones',
    'home.services.investments.description': 'Marcos de inversión seguros y transparentes con retornos ajustados al riesgo.',
    'home.services.financing.title': 'Soluciones de Financiamiento',
    'home.services.financing.description': 'Financiamiento competitivo con opciones sin intereses para sus proyectos de remodelación.',
    'home.simulator.cta': 'Probar Nuestro Simulador',
    'home.learnMore': 'Saber Más',
    'home.news.title': 'Noticias y Actualizaciones – Marzo 2025',
    'home.news.content': 'Nuevos Insights del Mercado: Nuestra última investigación destaca tendencias emergentes en la gestión de propiedades que están revolucionando la industria. Vuelva mensualmente para actualizaciones frescas y estrategias accionables.',
    
    // About page
    'about.hero.badge': 'Acerca de WM Management',
    'about.hero.title': 'Transformando Desafíos Inmobiliarios en Oportunidades',
    'about.hero.subtitle': 'Aprovechamos insights basados en datos y profunda experiencia de la industria para entregar soluciones que agregan valor real a cada relación con el cliente.',
    'about.mission.title': 'Nuestra Misión',
    'about.mission.content1': 'En WM Management & Investments, nuestra misión es convertir los desafíos inmobiliarios en oportunidades tangibles. Aprovechamos insights basados en datos y profunda experiencia de la industria para entregar soluciones que agregan valor real.',
    'about.mission.content2': 'Creemos que al abrazar la transparencia, integridad y un enfoque pragmático, podemos empoderar a cada inversor para alcanzar su máximo potencial.',
    'about.vision.title': 'Nuestra Visión',
    'about.vision.content': 'Nuestra visión es ser el socio de confianza que simplifica el complejo mundo de los bienes raíces, permitiendo a nuestros clientes tomar decisiones informadas y lograr un éxito duradero.',
    'about.team.title': 'Conoce Nuestro Equipo',
    'about.team.subtitle': 'Nuestro equipo es nuestra piedra angular. Compuesto por veteranos de la industria y estrategas innovadores, reunimos una gran riqueza de experiencia e ideas frescas para impulsar el éxito.',
    'about.team.leadership': 'Equipo de Liderazgo',
    'about.team.leadership.desc': 'Veteranos de la industria con décadas de experiencia combinada en gestión inmobiliaria e inversión.',
    'about.team.strategy': 'Expertos en Estrategia',
    'about.team.strategy.desc': 'Analistas de datos y planificadores estratégicos que transforman insights del mercado en oportunidades accionables.',
    'about.team.client': 'Socios de Clientes',
    'about.team.client.desc': 'Profesionales dedicados que trabajan lado a lado con los clientes para crear soluciones efectivas e innovadoras.',
    'about.values.title': 'Nuestros Valores Fundamentales',
    'about.values.subtitle': 'Los principios que guían cada decisión e impulsan nuestro éxito',
    'about.values.transparency': 'Transparencia',
    'about.values.transparency.desc': 'Comunicación clara y reportes honestos en cada interacción y transacción.',
    'about.values.integrity': 'Integridad',
    'about.values.integrity.desc': 'Prácticas éticas y toma de decisiones basada en principios que construye confianza duradera.',
    'about.values.excellence': 'Excelencia',
    'about.values.excellence.desc': 'Comprometidos a entregar resultados excepcionales a través de la mejora continua e innovación.',
    
    // Services page
    'services.hero.badge': 'Servicios Profesionales',
    'services.hero.title': 'Soluciones Inmobiliarias Integrales',
    'services.hero.subtitle': 'Nuestros servicios están en el corazón de lo que hacemos. Cada oferta está diseñada para entregar claridad, impulsar valor y proporcionar resultados medibles.',
    'services.property.title': 'Gestión de Propiedades',
    'services.property.description': 'Gestionar su propiedad no debería ser complicado. Nuestro servicio de gestión de propiedades cubre todo desde la administración de arrendamientos y mantenimiento rutinario hasta la optimización estratégica del rendimiento.',
    'services.brokerage.title': 'Corretaje',
    'services.brokerage.description': 'Las transacciones inmobiliarias exigen precisión y transparencia. Nuestros servicios de corretaje conectan compradores, vendedores y arrendatarios con las mejores oportunidades disponibles.',
    'services.consulting.title': 'Servicios de Consultoría',
    'services.consulting.description': 'Cuando la complejidad se encuentra con la claridad, el éxito sigue. Nuestros servicios de consultoría descomponen los desafíos inmobiliarios en estrategias claras y accionables.',
    'services.development.title': 'Desarrollo Inmobiliario',
    'services.development.description': 'Convirtiendo visión en realidad—nuestro equipo de desarrollo inmobiliario gestiona proyectos desde el concepto hasta la finalización con diseño innovador y planificación estratégica.',
    'services.investments.title': 'Fideicomisos e Inversiones',
    'services.investments.description': 'Invierta con seguridad. Nuestros servicios de fideicomiso e inversión proporcionan un marco seguro y transparente para gestionar activos inmobiliarios.',
    'services.property.features.lease': 'Administración de Arrendamientos',
    'services.property.features.maintenance': 'Gestión de Mantenimiento',
    'services.property.features.performance': 'Optimización del Rendimiento',
    'services.property.features.reporting': 'Reportes Financieros',
    'services.property.cta': 'Descubra Cómo Maximizamos el Valor de la Propiedad',
    'services.brokerage.features.analysis': 'Análisis de Mercado',
    'services.brokerage.features.transaction': 'Gestión de Transacciones',
    'services.brokerage.features.negotiations': 'Negociaciones Expertas',
    'services.brokerage.features.diligence': 'Soporte de Debida Diligencia',
    'services.brokerage.cta': 'Explorar Oportunidades Actuales',
    'services.consulting.features.feasibility': 'Estudios de Viabilidad',
    'services.consulting.features.legal': 'Asesoría Legal',
    'services.consulting.features.planning': 'Planificación Estratégica',
    'services.consulting.features.research': 'Investigación de Mercado',
    'services.consulting.cta': 'Solicitar Su Consulta',
    'services.development.features.project': 'Gestión de Proyectos',
    'services.development.features.design': 'Integración de Diseño',
    'services.development.features.construction': 'Supervisión de Construcción',
    'services.development.features.quality': 'Aseguramiento de Calidad',
    'services.development.cta': 'Descubrir Nuestros Proyectos de Desarrollo',
    'services.investments.features.portfolio': 'Gestión de Portafolio',
    'services.investments.features.risk': 'Evaluación de Riesgos',
    'services.investments.features.strategy': 'Estrategia de Inversión',
    'services.investments.features.monitoring': 'Monitoreo del Rendimiento',
    'services.investments.cta': 'Descubrir Más Sobre Nuestras Soluciones de Inversión',
    'services.card.description': 'Servicios profesionales de {service} adaptados a sus necesidades y objetivos específicos.',
    'services.news.title': 'Noticias y Actualizaciones – Marzo 2025',
    'services.news.subtitle': 'Últimos desarrollos en nuestros servicios',
    'services.cta.description': 'Permítanos ayudarle a transformar sus desafíos inmobiliarios en oportunidades estratégicas.',
    
    // Common
    'common.readyToStart': '¿Listo para Comenzar?',
    'common.contactTeam': 'Contactar Nuestro Equipo',
    'common.keyFeatures': 'Características Clave:',
    'common.language': 'Idioma',
    'common.trySimulator': 'Probar Nuestro Simulador',
    
    // Footer
    'footer.description': 'Transformando la complejidad en claridad. Su socio de confianza en consultoría, inversión y desarrollo inmobiliario.',
    
    // Industries & Programs page
    'industries.hero.badge': 'Industrias y Programas',
    'industries.hero.title': 'Gestión de Propiedades Across Industrias',
    'industries.hero.subtitle': 'Desde bases residenciales hasta sectores comerciales especializados, entregamos soluciones integrales de gestión de propiedades adaptadas a los requisitos únicos de cada industria.',
    'industries.overview.title': 'Desde Residencial a Sectores Especializados',
    'industries.overview.subtitle': 'Nuestra experiencia en gestión abarca desde propiedades residenciales hasta instalaciones comerciales e institucionales complejas',
    'industries.overview.description': 'Comenzando con una base sólida en gestión de propiedades residenciales, hemos expandido nuestra experiencia para servir diversas industrias. Nuestro enfoque integral asegura que ya sea que posea una casa unifamiliar o una instalación industrial compleja, proporcionamos el mismo nivel de gestión profesional y optimización estratégica.',
    'industries.sectors.title': 'Gestión Especializada por Industria',
    'industries.sectors.subtitle': 'Soluciones dirigidas para requisitos y desafíos específicos de la industria',
    'industries.residential.title': 'Propiedades Residenciales',
    'industries.residential.description': 'Gestión integral de casas unifamiliares, condominios y propiedades residenciales multifamiliares. Nos enfocamos en la satisfacción del inquilino, mantenimiento de propiedades y maximización de retornos de alquiler mientras preservamos el valor de la propiedad.',
    'industries.residential.cta': 'Explorar Gestión Residencial',
    'industries.commercial.title': 'Propiedades Comerciales',
    'industries.commercial.description': 'Gestión profesional de edificios de oficinas, espacios comerciales y desarrollos de uso mixto. Optimizamos la satisfacción del inquilino, maximizamos las tasas de ocupación y aseguramos que las propiedades operen eficientemente manteniendo fuertes retornos para los inversionistas.',
    'industries.commercial.cta': 'Explorar Gestión Comercial',
    'industries.health.title': 'Instalaciones de Salud',
    'industries.health.description': 'Gestión especializada para instalaciones médicas, clínicas y complejos de salud. Entendemos la importancia crítica del cumplimiento, la seguridad del paciente y la eficiencia operativa en entornos de salud.',
    'industries.health.cta': 'Descubrir Soluciones de Salud',
    'industries.industrial.title': 'Industrial y Manufactura',
    'industries.industrial.description': 'Gestión de almacenes, instalaciones de manufactura y centros de distribución. Nos enfocamos en la eficiencia operativa, cumplimiento de seguridad y mantenimiento de la infraestructura especializada que estas propiedades requieren.',
    'industries.industrial.cta': 'Conocer Gestión Industrial',
    'industries.logistics.title': 'Logística y Distribución',
    'industries.logistics.description': 'Gestión estratégica de centros logísticos y centros de distribución. Nuestro enfoque optimiza el flujo de tráfico, la eficiencia de carga y las operaciones de inquilinos manteniendo los altos estándares requeridos para el éxito de la cadena de suministro.',
    'industries.logistics.cta': 'Optimizar Su Propiedad Logística',
    'industries.governments.title': 'Gobierno e Institucional',
    'industries.governments.description': 'Gestión de edificios gubernamentales, instituciones educativas e instalaciones públicas. Proporcionamos gestión confiable y rentable mientras aseguramos el cumplimiento con los requisitos del sector público y manteniendo estándares comunitarios.',
    'industries.governments.cta': 'Ver Gestión del Sector Público',
    'industries.stats.title': 'Nuestro Historial',
    'industries.stats.subtitle': 'Resultados comprobados en múltiples industrias',
    'industries.stats.projects': 'Proyectos Completados',
    'industries.stats.clients': 'Socios de la Industria',
    'industries.stats.years': 'Años de Experiencia',
    'industries.news.title': 'Noticias y Actualizaciones – Marzo 2025',
    'industries.news.subtitle': 'Últimos insights de la industria',
    'industries.news.content': 'Reporte de Tendencias Urbanas: Nuestros últimos insights de la investigación económica urbana de primer nivel revelan estrategias innovadoras para la planificación urbana moderna. Manténgase actualizado para más hallazgos revolucionarios cada mes.',
    
    // FAQ page
    'faq.hero.badge': 'Preguntas Frecuentes',
    'faq.hero.title': 'Preguntas Frecuentes',
    'faq.hero.subtitle': 'Entendemos que la claridad es clave. Aquí encontrará respuestas directas a nuestras preguntas más comunes sobre nuestros servicios, financiamiento y procesos.',
    'faq.services.category': 'Servicios',
    'faq.services.q1.question': '¿Qué servicios ofrece WM Management & Investments?',
    'faq.services.q1.answer': 'Ofrecemos soluciones inmobiliarias integrales incluyendo gestión de propiedades, servicios de corretaje, consultoría, desarrollo inmobiliario y servicios de fideicomiso e inversión.',
    'faq.services.q2.question': '¿Cómo aseguran la calidad en la gestión de propiedades?',
    'faq.services.q2.answer': 'Nuestro servicio de gestión de propiedades cubre todo desde la administración de arrendamientos y mantenimiento rutinario hasta la optimización estratégica del rendimiento, asegurando que cada propiedad opere con máxima eficiencia.',
    'faq.services.q3.question': '¿Qué hace diferentes sus servicios de consultoría?',
    'faq.services.q3.answer': 'Nuestros servicios de consultoría descomponen los complejos desafíos inmobiliarios en estrategias claras y accionables, aprovechando insights basados en datos y profunda experiencia de la industria.',
    'faq.financing.category': 'Financiamiento',
    'faq.financing.q1.question': '¿Qué opciones de financiamiento ofrecen?',
    'faq.financing.q1.answer': 'Ofrecemos financiamiento competitivo con opciones sin intereses para hasta el 50% de sus costos de remodelación, con términos flexibles hasta 60 meses.',
    'faq.financing.q2.question': '¿Cómo funciona el proceso de aprobación de financiamiento?',
    'faq.financing.q2.answer': 'Nuestro proceso de aprobación simplificado está diseñado para tomar decisiones rápidas. Proporcionamos aprobación rápida con precios transparentes y sin costos ocultos.',
    'faq.financing.q3.question': '¿Puedo usar el simulador antes de aplicar?',
    'faq.financing.q3.answer': '¡Sí! Nuestro simulador interactivo le permite experimentar con diferentes escenarios de financiamiento en tiempo real para ayudarle a planificar con confianza.',
    'faq.investments.category': 'Inversiones',
    'faq.investments.q1.question': '¿Qué tipos de oportunidades de inversión proporcionan?',
    'faq.investments.q1.answer': 'Nuestros servicios de fideicomiso e inversión proporcionan un marco seguro y transparente para gestionar activos inmobiliarios, entregando retornos sostenibles ajustados al riesgo.',
    'faq.investments.q2.question': '¿Cómo aseguran la seguridad de las inversiones?',
    'faq.investments.q2.answer': 'Combinamos experiencia financiera con insights profundos del mercado y mantenemos estrictos estándares de transparencia para asegurar marcos de inversión seguros.',
    'faq.support.title': '¿Aún Tiene Preguntas?',
    'faq.support.subtitle': 'Nuestro equipo está a solo un clic para proporcionar asistencia personalizada.',
    'faq.support.contact': 'Contáctanos',
    'faq.support.call': 'Llámanos',
    'faq.news.title': 'Noticias y Actualizaciones – Marzo 2025',
    'faq.news.subtitle': 'Últimas actualizaciones de FAQ',
    'faq.news.content': 'Nuevas Preguntas FAQ: Basado en comentarios de clientes, hemos agregado respuestas a las últimas preguntas sobre nuestros procesos de consultoría y financiamiento.',
    
    // Financing page translations
    'financing.hero.badge': 'Soluciones de Financiamiento',
    'financing.hero.title': 'Financiamiento Inteligente para Su Éxito',
    'financing.hero.subtitle': 'Nuestras soluciones de financiamiento están diseñadas para derribar barreras y acelerar el crecimiento, ofreciendo opciones claras y accesibles para cada proyecto.',
    'financing.program.title': 'El Programa',
    'financing.program.description1': 'Nuestro programa de financiamiento está diseñado con simplicidad y eficiencia en mente. Con tarifas de configuración competitivas y financiamiento sin intereses para el 50% de sus costos de remodelación, eliminamos obstáculos y le empoderamos para avanzar con confianza.',
    'financing.program.description2': 'Creemos en crear caminos claros hacia el éxito eliminando la complejidad financiera innecesaria.',
    'financing.program.cta': 'Descubrir el Programa',
    'financing.simulator.title': 'Simulador Interactivo',
    'financing.simulator.description': 'La transparencia es clave para el financiamiento inteligente. Nuestro simulador interactivo le permite experimentar con diferentes escenarios de financiamiento en tiempo real.',
    'financing.simulator.cta': 'Probar el Simulador Ahora',
    'financing.signup.title': 'Inscríbase Hoy',
    'financing.signup.description': 'Únase a nuestro programa de financiamiento y dé el primer paso hacia lograr sus objetivos inmobiliarios con confianza y claridad.',
    'financing.signup.ready': '¿Listo para Comenzar?',
    'financing.signup.subtitle': 'Ya sea inversor, franquiciado o propietario, inscríbase en nuestro programa de financiamiento',
    'financing.signup.description2': '¿Listo para convertir el potencial en rendimiento? Inscríbase en nuestro programa de financiamiento y reciba orientación personalizada de nuestros expertos. Estamos comprometidos a hacer realidad su visión a través de pasos claros y de apoyo.',
    'financing.signup.cta1': 'Inscribirse en el Programa de Financiamiento',
    'financing.signup.cta2': 'Probar el Simulador Primero',
    'financing.news.title': 'Noticias y Actualizaciones – Marzo 2025',
    'financing.news.subtitle': 'Últimas mejoras a nuestras soluciones de financiamiento',
    'financing.news.content': 'Simulador Mejorado: Nuestra herramienta ahora incluye los últimos datos económicos para proporcionar proyecciones de inversión aún más precisas. ¡Explore las nuevas características y vea la diferencia hoy!',
    
    // Contact page translations
    'contact.hero.badge': 'Contáctanos',
    'contact.hero.title': 'Ponte en Contacto',
    'contact.hero.subtitle': 'Estamos aquí para ayudarte a transformar tus ideas en éxito accionable. Ya sea que tengas preguntas sobre nuestros servicios, opciones de financiamiento o necesites asesoría personalizada, por favor contáctanos.',
    'contact.form.title': 'Envíanos un Mensaje',
    'contact.form.subtitle': 'Completa el formulario y nuestro equipo te contactará en 48 horas',
    'contact.form.name': 'Nombre Completo',
    'contact.form.email': 'Dirección de Email',
    'contact.form.phone': 'Número de Teléfono',
    'contact.form.company': 'Empresa (Opcional)',
    'contact.form.message': 'Mensaje',
    'contact.form.send': 'Enviar Mensaje',
    'contact.info.title': 'Información de Contacto',
    'contact.info.subtitle': 'Nuestro equipo está listo para proporcionar asistencia clara y rápida. Su éxito es nuestra prioridad.',
    'contact.news.title': 'Noticias y Actualizaciones – Marzo 2025',
    'contact.news.subtitle': 'Opciones de soporte mejoradas',
    'contact.news.content': 'Chat en Vivo Ahora Disponible: Hemos extendido nuestras horas de soporte en vivo para asegurar que reciba asistencia inmediata cuando la necesite.',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
