import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
import { Resend } from "npm:resend@4.0.0";
import { encode as base64Encode } from "https://deno.land/std@0.190.0/encoding/base64.ts";
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? '';
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
const resendApiKey = Deno.env.get('RESEND_API_KEY') ?? '';

const supabase = createClient(supabaseUrl, supabaseServiceKey);
const resend = new Resend(resendApiKey);

interface ExportRequest {
  email: string;
  simulationData: {
    items: any[];
    creditLines?: any[];
    estimatedMonthlyIncome?: number;
    grossMarginPercentage?: number;
  };
  analysisResults: any;
  language?: 'en' | 'es';
}

const generatePDFContent = (items: any[], analysisResults: any, referenceNumber: string, language: 'en' | 'es' = 'en', creditLines: any[] = [], estimatedMonthlyIncome = 0, grossMarginPercentage = 30) => {
  const selectedItems = items.filter((item: any) => item.isSelected);
  const netMonthlyIncome = estimatedMonthlyIncome * (grossMarginPercentage / 100);
  const debtToIncomeRatio = estimatedMonthlyIncome > 0 ? (analysisResults.monthlyPaymentTotal / netMonthlyIncome) * 100 : 0;
  
  // Translations
  const t = {
    en: {
      title: 'Investment Simulation Report',
      executiveSummary: 'Executive Summary',
      totalInvestment: 'Total Investment',
      totalFinanced: 'Total Financed',
      upfrontPayment: 'Upfront Payment',
      monthlyPayment: 'Monthly Payment',
      roi: 'Return on Investment',
      breakEven: 'Break-even Period',
      paybackPeriod: 'Payback Period',
      selectedItems: 'Selected Investment Items',
      item: 'Item',
      amount: 'Amount',
      advance: 'Advance',
      financed: 'Financed',
      creditType: 'Credit Type',
      incomeConfig: 'Income Configuration',
      estimatedIncome: 'Estimated Monthly Income',
      grossMargin: 'Gross Margin',
      netIncome: 'Net Monthly Income',
      debtToIncome: 'Debt-to-Income Ratio',
      financingSources: 'Financing Sources',
      creditAmount: 'Credit Amount',
      interestRate: 'Interest Rate',
      termMonths: 'Term (Months)',
      monthlyPmt: 'Monthly Payment',
      analysisResults: 'Financial Analysis',
      breakEvenDesc: 'Time required to recover initial investment',
      roiDesc: 'Annual return on investment percentage',
      paybackDesc: 'Time to recover the total investment',
      disclaimer: 'Legal Notice – Investment Plan Simulator',
      disclaimerContent: [
        'The investment plan simulator available on this website is a resource of an exclusively illustrative and guidance nature. The values, calculations, projections and results generated by the tool constitute estimates that do not necessarily reflect real market conditions, nor conditions offered by banking, financial or other credit organizations.',
        'WM Management S.A. does not guarantee the accuracy, validity or applicability of the data resulting from this simulator, and assumes no responsibility for investment, financing or any other decisions that users make based on the information obtained here.',
        'The use of the simulator does not replace professional advice. We strongly recommend that users consult with financial, accounting and legal advisors before making decisions related to investments or credit contracting.',
        'By using this simulator, the user acknowledges and accepts that WM Management S.A. will not be responsible for losses, damages or consequences derived directly or indirectly from the use of this tool.'
      ],
      months: 'months',
      year: 'year'
    },
    es: {
      title: 'Reporte de Simulación de Inversión',
      executiveSummary: 'Resumen Ejecutivo',
      totalInvestment: 'Inversión Total',
      totalFinanced: 'Total Financiado',
      upfrontPayment: 'Pago Inicial',
      monthlyPayment: 'Pago Mensual',
      roi: 'Retorno de Inversión',
      breakEven: 'Punto de Equilibrio',
      paybackPeriod: 'Período de Recuperación',
      selectedItems: 'Elementos de Inversión Seleccionados',
      item: 'Elemento',
      amount: 'Monto',
      advance: 'Adelanto',
      financed: 'Financiado',
      creditType: 'Tipo de Crédito',
      incomeConfig: 'Configuración de Ingresos',
      estimatedIncome: 'Ingresos Mensuales Estimados',
      grossMargin: 'Margen Bruto',
      netIncome: 'Ingresos Mensuales Netos',
      debtToIncome: 'Relación Deuda-Ingreso',
      financingSources: 'Fuentes de Financiamiento',
      creditAmount: 'Monto del Crédito',
      interestRate: 'Tasa de Interés',
      termMonths: 'Plazo (Meses)',
      monthlyPmt: 'Pago Mensual',
      analysisResults: 'Análisis Financiero',
      breakEvenDesc: 'Tiempo requerido para recuperar la inversión inicial',
      roiDesc: 'Porcentaje de retorno anual sobre la inversión',
      paybackDesc: 'Tiempo para recuperar la inversión total',
      disclaimer: 'Aviso Legal – Simulador de Plan de Inversión',
      disclaimerContent: [
        'El simulador de plan de inversión disponible en este sitio web es un recurso de carácter exclusivamente ilustrativo y orientativo. Los valores, cálculos, proyecciones y resultados generados por la herramienta constituyen estimaciones que no necesariamente reflejan condiciones reales de mercado, ni condiciones ofrecidas por entidades bancarias, financieras u otras organizaciones crediticias.',
        'WM Management S.A. no garantiza la exactitud, vigencia ni aplicabilidad de los datos que resulten de este simulador, y no asume responsabilidad alguna por las decisiones de inversión, financiamiento o cualquier otra índole que los usuarios adopten en base a la información aquí obtenida.',
        'El uso del simulador no sustituye el asesoramiento profesional. Recomendamos enfáticamente que los usuarios consulten con asesores financieros, contables y legales antes de tomar decisiones relacionadas con inversiones o contratación de créditos.',
        'Al utilizar este simulador, el usuario reconoce y acepta que WM Management S.A. no será responsable por pérdidas, daños o consecuencias derivadas directa o indirectamente del uso de esta herramienta.'
      ],
      months: 'meses',
      year: 'año'
    }
  };
  
  const trans = t[language];
  
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${trans.title} - ${referenceNumber}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; line-height: 1.6; }
    .header { text-align: center; border-bottom: 2px solid #3b82f6; padding-bottom: 20px; margin-bottom: 30px; }
    .logo { font-size: 24px; font-weight: bold; color: #3b82f6; }
    .ref-number { font-size: 14px; color: #666; margin-top: 10px; }
    .section { margin-bottom: 40px; page-break-inside: avoid; }
    .section h2 { color: #3b82f6; border-bottom: 1px solid #e5e7eb; padding-bottom: 10px; margin-bottom: 20px; }
    .section h3 { color: #1f2937; margin-bottom: 15px; }
    .summary-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin: 20px 0; }
    .metric-card { padding: 20px; border: 1px solid #e5e7eb; border-radius: 8px; background: #f9fafb; }
    .metric-value { font-size: 28px; font-weight: bold; color: #3b82f6; margin-bottom: 5px; }
    .metric-label { font-size: 14px; color: #666; }
    .items-table, .credit-table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    .items-table th, .items-table td, .credit-table th, .credit-table td { 
      padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; 
    }
    .items-table th, .credit-table th { 
      background-color: #f3f4f6; font-weight: bold; color: #374151; 
    }
    .items-table tr:nth-child(even), .credit-table tr:nth-child(even) { 
      background-color: #f9fafb; 
    }
    .config-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 20px 0; }
    .config-item { padding: 15px; border: 1px solid #d1d5db; border-radius: 6px; background: #ffffff; }
    .config-label { font-weight: bold; color: #374151; margin-bottom: 5px; }
    .config-value { font-size: 18px; color: #3b82f6; font-weight: bold; }
    .disclaimer { 
      background: #fef3c7; 
      border: 1px solid #f59e0b; 
      border-radius: 8px; 
      padding: 25px; 
      margin: 30px 0; 
      page-break-inside: avoid;
    }
    .disclaimer h3 { color: #92400e; margin-bottom: 15px; }
    .disclaimer p { margin-bottom: 15px; text-align: justify; }
    .disclaimer p:last-child { margin-bottom: 0; }
    .footer { 
      margin-top: 50px; 
      text-align: center; 
      font-size: 12px; 
      color: #666; 
      border-top: 1px solid #e5e7eb; 
      padding-top: 20px; 
    }
    .analysis-item { 
      padding: 15px; 
      border-left: 4px solid #3b82f6; 
      background: #f8fafc; 
      margin: 10px 0; 
    }
    .analysis-title { font-weight: bold; color: #1f2937; margin-bottom: 5px; }
    .analysis-description { color: #64748b; font-size: 14px; }
    @media print {
      body { margin: 20px; }
      .page-break { page-break-before: always; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">WM Management</div>
    <h1>${trans.title}</h1>
    <div class="ref-number">${language === 'en' ? 'Reference' : 'Referencia'}: ${referenceNumber}</div>
    <div class="ref-number">${language === 'en' ? 'Generated' : 'Generado'}: ${new Date().toLocaleDateString(language === 'es' ? 'es-ES' : 'en-US')}</div>
  </div>

  <div class="section">
    <h2>${trans.executiveSummary}</h2>
    <div class="summary-grid">
      <div class="metric-card">
        <div class="metric-value">$${Math.round(analysisResults.totalInvestment).toLocaleString()}</div>
        <div class="metric-label">${trans.totalInvestment}</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">$${Math.round(analysisResults.totalAdvances).toLocaleString()}</div>
        <div class="metric-label">${trans.upfrontPayment}</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">$${Math.round(analysisResults.totalFinanced).toLocaleString()}</div>
        <div class="metric-label">${trans.totalFinanced}</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">$${Math.round(analysisResults.monthlyPaymentTotal).toLocaleString()}</div>
        <div class="metric-label">${trans.monthlyPayment}</div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>${trans.incomeConfig}</h2>
    <div class="config-grid">
      <div class="config-item">
        <div class="config-label">${trans.estimatedIncome}</div>
        <div class="config-value">$${Math.round(estimatedMonthlyIncome).toLocaleString()}</div>
      </div>
      <div class="config-item">
        <div class="config-label">${trans.grossMargin}</div>
        <div class="config-value">${grossMarginPercentage}%</div>
      </div>
      <div class="config-item">
        <div class="config-label">${trans.netIncome}</div>
        <div class="config-value">$${Math.round(netMonthlyIncome).toLocaleString()}</div>
      </div>
      <div class="config-item">
        <div class="config-label">${trans.debtToIncome}</div>
        <div class="config-value">${debtToIncomeRatio.toFixed(1)}%</div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>${trans.selectedItems}</h2>
    <table class="items-table">
      <thead>
        <tr>
          <th>${trans.item}</th>
          <th>${trans.amount}</th>
          <th>${trans.advance}</th>
          <th>${trans.financed}</th>
          <th>${trans.creditType}</th>
        </tr>
      </thead>
      <tbody>
        ${selectedItems.map((item: any) => `
          <tr>
            <td>${item.name}</td>
            <td>$${Math.round(item.amount).toLocaleString()}</td>
            <td>$${Math.round(item.advanceAmount).toLocaleString()}</td>
            <td>$${Math.round(item.financeBalance).toLocaleString()}</td>
            <td style="text-transform: capitalize;">${item.creditType}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </div>

  ${creditLines.length > 0 ? `
  <div class="section">
    <h2>${trans.financingSources}</h2>
    <table class="credit-table">
      <thead>
        <tr>
          <th>${trans.creditType}</th>
          <th>${trans.creditAmount}</th>
          <th>${trans.interestRate}</th>
          <th>${trans.termMonths}</th>
          <th>${trans.monthlyPmt}</th>
        </tr>
      </thead>
      <tbody>
        ${creditLines.map((credit: any) => `
          <tr>
            <td style="text-transform: capitalize;">${credit.type}</td>
            <td>$${Math.round(credit.totalAmount).toLocaleString()}</td>
            <td>${credit.interestRate}%</td>
            <td>${credit.termMonths}</td>
            <td>$${Math.round(credit.monthlyPayment).toLocaleString()}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </div>
  ` : ''}

  <div class="section page-break">
    <h2>${trans.analysisResults}</h2>
    <div class="analysis-item">
      <div class="analysis-title">${trans.breakEven}: ${Math.round(analysisResults.breakEvenMonths)} ${trans.months}</div>
      <div class="analysis-description">${trans.breakEvenDesc}</div>
    </div>
    <div class="analysis-item">
      <div class="analysis-title">${trans.roi}: ${analysisResults.roi}% ${language === 'en' ? 'per' : 'por'} ${trans.year}</div>
      <div class="analysis-description">${trans.roiDesc}</div>
    </div>
    <div class="analysis-item">
      <div class="analysis-title">${trans.paybackPeriod}: ${analysisResults.paybackPeriod.toFixed(1)} ${trans.year}${analysisResults.paybackPeriod > 1 ? 's' : ''}</div>
      <div class="analysis-description">${trans.paybackDesc}</div>
    </div>
  </div>

  <div class="disclaimer">
    <h3>${trans.disclaimer}</h3>
    ${trans.disclaimerContent.map((content: string) => `<p>${content}</p>`).join('')}
  </div>

  <div class="footer">
    <p>${language === 'en' ? 'This report was generated automatically by the WM Management investment simulation system.' : 'Este reporte fue generado automáticamente por el sistema de simulación de inversiones de WM Management.'}</p>
    <p>${language === 'en' ? 'For questions or support, please contact our team.' : 'Para preguntas o soporte, por favor contacte a nuestro equipo.'}</p>
    <p>WM Management S.A. | Email: info@wmmanagement.com | ${language === 'en' ? 'Phone' : 'Teléfono'}: +1 234 567 8900</p>
  </div>
</body>
</html>
  `;
};

const handler = async (req: Request): Promise<Response> => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { 
      email, 
      simulationData, 
      analysisResults, 
      language = 'en'
    }: ExportRequest = await req.json();

    const { items, creditLines = [], estimatedMonthlyIncome = 0, grossMarginPercentage = 30 } = simulationData;

    console.log('Processing PDF export request for:', email);
    console.log('Resend API key available:', !!resendApiKey);
    console.log('Resend API key available:', !!resendApiKey);
    console.log('Resend API key length:', resendApiKey?.length || 'undefined');

    if (!resendApiKey) {
      throw new Error('RESEND_API_KEY environment variable is not set');
    }
    if (!resendApiKey.startsWith('re_')) {
      throw new Error('RESEND_API_KEY appears invalid. It must start with "re_".');
    }

    // Generate reference number
    console.log('Generating reference number...');
    const { data: refData, error: refError } = await supabase.rpc('generate_reference_number');
    if (refError) {
      console.error('Reference number generation error:', refError);
      throw new Error(`Failed to generate reference number: ${refError.message}`);
    }
    const referenceNumber = refData || `SIM-${Date.now()}`;
    console.log('Generated reference number:', referenceNumber);

    // Save simulation to database
    const { data: simulation, error: simError } = await supabase
      .from('investment_simulations')
      .insert({
        reference_number: referenceNumber,
        user_email: email,
        simulation_data: {
          items,
          creditLines,
          estimatedMonthlyIncome,
          grossMarginPercentage
        },
        analysis_results: analysisResults
      })
      .select()
      .single();

    if (simError) {
      console.error('Database error:', simError);
      throw new Error('Failed to save simulation');
    }

    // Create PDF request record
    const { error: requestError } = await supabase
      .from('pdf_report_requests')
      .insert({
        simulation_id: simulation.id,
        user_email: email,
        status: 'processing'
      });

    if (requestError) {
      console.error('PDF request error:', requestError);
    }

    // Generate PDF content
    const htmlContent = generatePDFContent(
      items, 
      analysisResults, 
      referenceNumber, 
      language, 
      creditLines, 
      estimatedMonthlyIncome, 
      grossMarginPercentage
    );

    // Send email with PDF report
    try {
      const emailResponse = await resend.emails.send({
        from: 'WM Management <onboarding@resend.dev>',
        to: [email],
        subject: language === 'es' 
          ? `Reporte de Simulación de Inversión - ${referenceNumber}`
          : `Investment Simulation Report - ${referenceNumber}`,
        html: htmlContent, // Send the full HTML report directly in email body
      });

      console.log('Email response:', emailResponse);

      // Check if email sending was successful
      if (emailResponse.error) {
        console.error('Resend API error:', emailResponse.error);
        throw new Error(`Email sending failed: ${emailResponse.error.message || 'Unknown error'}`);
      }

      // Update request status to completed
      await supabase
        .from('pdf_report_requests')
        .update({ 
          status: 'completed',
          completed_at: new Date().toISOString()
        })
        .eq('simulation_id', simulation.id);

    } catch (emailError: any) {
      console.error('Email sending failed:', emailError);
      
      // Update request status to failed
      await supabase
        .from('pdf_report_requests')
        .update({ 
          status: 'failed',
          error_message: emailError.message
        })
        .eq('simulation_id', simulation.id);

      throw new Error(`Failed to send email: ${emailError.message}`);
    }

    return new Response(JSON.stringify({ 
      success: true,
      referenceNumber,
      simulationId: simulation.id
    }), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        ...corsHeaders,
      },
    });

  } catch (error: any) {
    console.error('Error in export-pdf-report function:', error);
    console.error('Error stack:', error.stack);
    console.error('Error name:', error.name);
    console.error('Error message:', error.message);
    
    return new Response(
      JSON.stringify({ 
        error: error.message,
        details: error.name,
        stack: error.stack
      }),
      {
        status: 500,
        headers: { 'Content-Type': 'application/json', ...corsHeaders },
      }
    );
  }
};

serve(handler);